<?php
/**
 * @brief url library french dictionary.
 * @details Engine / Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0pre0.1
 * @date Creation: Mar 2021
 * @date Modification: Jun 2021
 * @copyright 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY,
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$locales = array(
    /* Base URL mode values */
    'BaseURLMode_Absolute_Long'     => 'Absolue, longue',
    'BaseURLMode_Absolute_Short'    => 'Absolue, courte',
    'BaseURLMode_Relative'          => 'Relative',

    /* SSL mode values */
    'SSLMode_HTTPS'     => 'Forc&eacute;e en HTTPS',
    'SSLMode_HTTP'      => 'Forc&eacute;e en HTTP',
    'SSLMode_Auto'      => 'Automatique',
    'SSLMode_Default'   => 'Libre (choix de l\'utilisateur)',
);
?>
