<?php
/**
 * @brief ErrorHandler library french dictionary.
 * @details Engine / Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0pre0
 * @date Creation: Mar 2021
 * @date Modification: Mar 2021
 * @copyright 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY,
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$locales = array(
    /* Output values */
    'Output_Auto'       => 'Automatique',
    'Output_HTML'       => 'Affich&eacute;es dans la page HTML',
    'Output_Logs'       => 'Enregistr&eacute;es dans les journaux du site',
    'Output_Shared'     => 'Enregistr&eacute;es dans un objet partag&eacute; de CaMykS',
    'Output_Session'    => 'Enregistr&eacute;es dans la session de l\'utilisateur',
    'Output_None'       => 'Aucune',

    /* Level values */
    'Level_Auto'        => 'Automatique',
    'Level_Mini'        => 'Minimum',
    'Level_Maxi'        => 'Maximum',
);
?>
