<?php
/**
 * @brief CaMykS currencies data stored by 3-letters codes (ISO 4217).
 * @details Engine / Data Library
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.0
 * @date Creation: Oct 2019
 * @date Modification: Oct 2019
 * @copyright 2019 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * @warning This library is not loaded with CaMykS initialisation.
 */
global $cCurrencies;

$cCurrencies = array(
    'aed' => array(), // United Arab Emirates dirham
    'afn' => array(), // Afghan afghani
    'all' => array(), // Albanian lek
    'amd' => array(), // Armenian dram
    'ang' => array(), // Netherlands Antillean guilder
    'aoa' => array(), // Angolan kwanza
    'ars' => array(), // Argentine peso
    'aud' => array(), // Australian dollar
    'awg' => array(), // Aruban florin
    'azn' => array(), // Azerbaijani manat
    'bam' => array(), // Bosnia and Herzegovina convertible mark
    'bbd' => array(), // Barbadian dollar
    'bdt' => array(), // Bangladeshi taka
    'bgn' => array(), // Bulgarian lev
    'bhd' => array(), // Bahraini dinar
    'bif' => array(), // Burundian franc
    'bmd' => array(), // Bermudian dollar
    'bnd' => array(), // Brunei dollar
    'bob' => array(), // Bolivian boliviano
    'brl' => array(), // Brazilian real
    'bsd' => array(), // Bahamian dollar
    'btn' => array(), // Bhutanese ngultrum
    'bwp' => array(), // Botswana pula
    'byn' => array(), // Belarusian ruble
    'bzd' => array(), // Belize dollar
    'cad' => array(), // Canadian dollar
    'cdf' => array(), // Congolese franc
    'chf' => array(), // Swiss franc
    'ckd' => array(), // Cook Islands dollar
    'clp' => array(), // Chilean peso
    'cny' => array(), // Chinese yuan
    'cop' => array(), // Colombian peso
    'crc' => array(), // Costa Rican colón
    'cup' => array(), // Cuban peso
    'cve' => array(), // Cape Verdean escudo
    'czk' => array(), // Czech koruna
    'djf' => array(), // Djiboutian franc
    'dkk' => array(), // Danish krone
    'dop' => array(), // Dominican peso
    'dzd' => array(), // Algerian dinar
    'egp' => array(), // Egyptian pound
    'ern' => array(), // Eritrean nakfa
    'etb' => array(), // Ethiopian birr
    'eur' => array(), // Euro
    'fjd' => array(), // Fijian dollar
    'fkp' => array(), // Falklands pound
    'gbp' => array(), // British pound
    'gel' => array(), // Georgian lari
    'ghs' => array(), // Ghanaian cedi
    'gip' => array(), // Gibraltar pound
    'gmd' => array(), // Gambian dalasi
    'gnf' => array(), // Guinean franc
    'gtq' => array(), // Guatemalan quetzal
    'gyd' => array(), // Guyanese dollar
    'hkd' => array(), // Hong Kong dollar
    'hnl' => array(), // Honduran lempira
    'hrk' => array(), // Croatian kuna
    'htg' => array(), // Haitian gourde
    'huf' => array(), // Hungarian forint
    'idr' => array(), // Indonesian rupiah
    'ils' => array(), // Israeli new shekel
    'inr' => array(), // Indian rupee
    'idq' => array(), // Iraqi dinar
    'irr' => array(), // Iranian rial
    'isk' => array(), // Icelandic króna
    'jmd' => array(), // Jamaican dollar
    'jod' => array(), // Jordanian dinar
    'jpy' => array(), // Japanese yen
    'kes' => array(), // Kenyan shilling
    'kgs' => array(), // Kyrgyzstani som
    'khr' => array(), // Cambodian riel
    'kmf' => array(), // Comorian franc
    'kpw' => array(), // North Korean won
    'krw' => array(), // South Korean won
    'kwd' => array(), // Kuwaiti dinar
    'kyd' => array(), // Caiman Islands dollar
    'kzt' => array(), // Kazakhstani tenge
    'lak' => array(), // Lao kip
    'lbp' => array(), // Lebanese pound
    'lkr' => array(), // Sri Lankan rupee
    'lrd' => array(), // Liberian dollar
    'lsl' => array(), // Lesotho loti
    'lyd' => array(), // Libyan dinar
    'mad' => array(), // Moroccan dirham
    'mdl' => array(), // Moldovan leu
    'mga' => array(), // Malagasy ariary
    'mkd' => array(), // Macedonian denar
    'mmk' => array(), // Burmese kyat
    'mnt' => array(), // Mongolian tögrög
    'mop' => array(), // Macanese pataca
    'mro' => array(), // Mauritanian ouguiya
    'mur' => array(), // Mauritian rupee
    'mvr' => array(), // Maldivian rufiyaa
    'mwk' => array(), // Malawian kwacha
    'mxn' => array(), // Mexican peso
    'myr' => array(), // Malaysian ringgit
    'mzn' => array(), // Mozambican metical
    'nad' => array(), // Namibian dollar
    'ngn' => array(), // Nigerian naira
    'nio' => array(), // Nicaraguan córdoba
    'nok' => array(), // Norwegian krone
    'npr' => array(), // Nepalese rupee
    'nzd' => array(), // New Zealand dollar
    'omr' => array(), // Omani rial
    'pab' => array(), // Panamanian balboa
    'pen' => array(), // Peruvian sol
    'pgk' => array(), // Papua New Guinean kina
    'php' => array(), // Philippine peso
    'pkr' => array(), // Pakistani rupee
    'pln' => array(), // Polish zloty
    'pyg' => array(), // Paraguayan guaraní
    'qar' => array(), // Qatari riyal
    'ron' => array(), // Romanian leu
    'rsd' => array(), // Serbian dinar
    'rub' => array(), // Russian ruble
    'rwf' => array(), // Rwandan franc
    'sar' => array(), // Saudi riyal
    'sbd' => array(), // Solomon Islands dollar
    'scr' => array(), // Seychellois rupee
    'sdg' => array(), // Sudanese pound
    'sek' => array(), // Swedish krona
    'sgd' => array(), // Singapore dollar
    'shp' => array(), // Saint Helena pound
    'sll' => array(), // Sierra Leonean leone
    'sos' => array(), // Somali shilling
    'srd' => array(), // Surinamese dollar
    'ssp' => array(), // South Sudanese pound
    'std' => array(), // São Tomé and Príncipe dobra
    'syp' => array(), // Syrian pound
    'szl' => array(), // Swazi lilangeni
    'thb' => array(), // Thai baht
    'tjs' => array(), // Tajikistani somoni
    'tmt' => array(), // Turkmenistan manat
    'tnd' => array(), // Tunisian dinar
    'top' => array(), // Tongan pa'anga
    'try' => array(), // Turkish lira
    'ttd' => array(), // Trinidad and Tobago dollar
    'twd' => array(), // New Taiwan dollar
    'tzs' => array(), // Tanzanian shilling
    'uah' => array(), // Ukrainian hryvnia
    'ugx' => array(), // Ugandan shilling
    'usd' => array(), // United States dollar
    'uyu' => array(), // Uruguayan peso
    'uzs' => array(), // Uzbekistani som
    'vef' => array(), // Venezuelan bolívar
    'vnd' => array(), // Vietnamese dong
    'vuv' => array(), // Vanuatu vatu
    'wst' => array(), // Samoan tala
    'xaf' => array(), // Central African CFA franc
    'xcd' => array(), // East Caribbean dollar
    'xof' => array(), // West African CFA franc
    'xpf' => array(), // CFP franc
    'yer' => array(), // Yemeni rial
    'zar' => array(), // South African rand
    'zmw' => array(), // Zambian kwacha
);
?>
