<?php
/**
 * @brief SystemUniqueIdManager plugin, french dictionary.
 * @details Plugin / Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0pre0
 * @date Creation: Feb 2022
 * @date Modification: Feb 2022
 * @copyright 2022 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY,
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$locales = array(
    /* Plugin title */
    'Title' => 'ID Uniques',

    /* Key object */
    'Key' => 'Identifiant unique',
    'Keys' => 'Identifiants uniques',
    'Keys_All' => 'Tous',
    'Keys_None' => 'Aucun',

    /* Key status */
    'KeyStatus_Free' => 'Libre',
    'KeyStatus_Used' => 'Utilis&eacute;',

    /* Key status */
    'KeysStatus_Free' => 'Libres',
    'KeysStatus_Used' => 'Utilis&eacute;s',
);
?>
