<?php
/**
 * @brief SystemAdministratorManager plugin, french dictionary.
 * @details Plugin / Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0pre0
 * @date Creation: Nov 2021
 * @date Modification: Nov 2021
 * @copyright 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY,
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$locales = array(

    /* Errors */
    'Error_AdminUserEmailIsEmpty' => 'L\'adresse e-mail de l\'administrateur ne peut pas être vide.',
    'Error_AdminUserEmailIsNotValid' => 'L\'adresse e-mail de l\'administrateur doit &ecirc;tre valide.',
    'Error_AdminUserPasswordIsEmpty' => 'Le mot de passe de l\'administrateur ne peut pas être vide.',
    'Error_AdminUserPasswordIsNotConfirmed' => 'Le mot de passe de l\'administrateur ne correspond pas &agrave; la confirmation.',
);
?>
