{
    "cv" : {
        "kw" : [
            {
                "operator" : "x",
                "value" : 0.735499
            },
            {
                "operator" : "round",
                "value" : 0
            }
        ]
    },
    "kw" : {
        "cv" : [
            {
                "operator" : "x",
                "value" : 1.3596
            },
            {
                "operator" : "round",
                "value" : 0
            }
        ]
    },
    "°c" : {
        "°f" : [
            {
                "operator" : "x",
                "value" : 9
            },
            {
                "operator" : "/",
                "value" : 5
            },
            {
                "operator" : "+",
                "value" : 32
            }
        ],
        "K" : [
            {
                "operator" : "+",
                "value" : 273.15
            }
        ]
    },
    "°f" : {
        "°c" : [
            {
                "operator" : "-",
                "value" : 32
            },
            {
                "operator" : "x",
                "value" : 5
            },
            {
                "operator" : "/",
                "value" : 9
            }
        ],
        "K" : [
            {
                "operator" : "-",
                "value" : 32
            },
            {
                "operator" : "x",
                "value" : 5
            },
            {
                "operator" : "/",
                "value" : 9
            },
            {
                "operator" : "+",
                "value" : 273.15
            }
        ]
    },
    "yd" : {
        "m" : [
            {
                "operator" : "x",
                "value" : 0.9144
            }
        ]
    },
    "m" : {
        "yd" : [
            {
                "operator" : "x",
                "value" : 1.093613
            }
        ],
        "km" : [
            {
                "operator" : "/",
                "value" : 1000
            }
        ],
        "cm" : [
            {
                "operator" : "x",
                "value" : 100
            }
        ]
    },
    "in" : {
        "cm" : [
            {
                "operator" : "x",
                "value" : 2.54
            }
        ]
    },
    "cm" : {
        "in" : [
            {
                "operator" : "x",
                "value" : 0.393701
            }
        ],
        "m" : [
            {
                "operator" : "/",
                "value" : 100
            }
        ]
    },
    "mi" : {
        "km" : [
            {
                "operator" : "x",
                "value" : 1.609344
            }
        ]
    },
    "km" : {
        "mi" : [
            {
                "operator" : "x",
                "value" : 0.621371
            }
        ],
        "m" : [
            {
                "operator" : "x",
                "value" : 1000
            }
        ]
    }
}
