{
    "Module": {
        "SystemConfigurationManager":"System",
        "SystemFileStorageManager":"System",
        "SystemAdministratorManager":"System",
        "SystemLogManager":"System",
        "SystemPluginManager":"System",
        "SystemPrivacyPolicyManager":"System",
        "SystemSecurityManager":"System",
        "SystemSessionManager":"System",
        "SystemSitePageManager":"System",
        "SystemUniqueIdManager":"System"
    },
    "Component": {

    }
}

