{
    "Africa/Abidjan": {
        "STZ"   : "Greenwich Mean Time",
        "DSTZ"  : ""
    },
    "Africa/Accra": {
        "STZ"   : "Greenwich Mean Time",
        "DSTZ"  : ""
    },
    "Africa/Addis_Ababa": {
        "STZ"   : "Eastern Africa Time",
        "DSTZ"  : ""
    },
    "Africa/Algiers": {
        "STZ"   : "Central European Time",
        "DSTZ"  : ""
    },
    "Africa/Asmara": {
        "STZ"   : "Eastern Africa Time",
        "DSTZ"  : ""
    },
    "Africa/Bamako": {
        "STZ"   : "Greenwich Mean Time",
        "DSTZ"  : ""
    },
    "Africa/Bangui": {
        "STZ"   : "West Africa Time",
        "DSTZ"  : ""
    },
    "Africa/Banjul": {
        "STZ"   : "Greenwich Mean Time",
        "DSTZ"  : ""
    },
    "Africa/Bissau": {
        "STZ"   : "Greenwich Mean Time",
        "DSTZ"  : ""
    },
    "Africa/Blantyre": {
        "STZ"   : "Central Africa Time",
        "DSTZ"  : ""
    },
    "Africa/Brazzaville": {
        "STZ"   : "West Africa Time",
        "DSTZ"  : ""
    },
    "Africa/Bujumbura": {
        "STZ"   : "Central Africa Time",
        "DSTZ"  : ""
    },
    "Africa/Cairo": {
        "STZ"   : "Eastern European Time",
        "DSTZ"  : ""
    },
    "Africa/Casablanca": {
        "STZ"   : "Western European Time",
        "DSTZ"  : "Western European Summer Time"
    },
    "Africa/Ceuta": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Africa/Conakry": {
        "STZ"   : "Greenwich Mean Time",
        "DSTZ"  : ""
    },
    "Africa/Dakar": {
        "STZ"   : "Greenwich Mean Time",
        "DSTZ"  : ""
    },
    "Africa/Dar_es_Salaam": {
        "STZ"   : "Eastern Africa Time",
        "DSTZ"  : ""
    },
    "Africa/Djibouti": {
        "STZ"   : "Eastern Africa Time",
        "DSTZ"  : ""
    },
    "Africa/Douala": {
        "STZ"   : "West Africa Time",
        "DSTZ"  : ""
    },
    "Africa/El_Aaiun": {
        "STZ"   : "Western European Time",
        "DSTZ"  : "Western European Summer Time"
    },
    "Africa/Freetown": {
        "STZ"   : "Greenwich Mean Time",
        "DSTZ"  : ""
    },
    "Africa/Gaborone": {
        "STZ"   : "Central Africa Time",
        "DSTZ"  : ""
    },
    "Africa/Harare": {
        "STZ"   : "Central Africa Time",
        "DSTZ"  : ""
    },
    "Africa/Johannesburg": {
        "STZ"   : "South African Standard Time",
        "DSTZ"  : ""
    },
    "Africa/Juba": {
        "STZ"   : "Central Africa Time",
        "DSTZ"  : ""
    },
    "Africa/Kampala": {
        "STZ"   : "Eastern Africa Time",
        "DSTZ"  : ""
    },
    "Africa/Khartoum": {
        "STZ"   : "Central Africa Time",
        "DSTZ"  : ""
    },
    "Africa/Kigali": {
        "STZ"   : "Central Africa Time",
        "DSTZ"  : ""
    },
    "Africa/Kinshasa": {
        "STZ"   : "West Africa Time",
        "DSTZ"  : ""
    },
    "Africa/Lagos": {
        "STZ"   : "West Africa Time",
        "DSTZ"  : ""
    },
    "Africa/Libreville": {
        "STZ"   : "West Africa Time",
        "DSTZ"  : ""
    },
    "Africa/Lome": {
        "STZ"   : "Greenwich Mean Time",
        "DSTZ"  : ""
    },
    "Africa/Luanda": {
        "STZ"   : "West Africa Time",
        "DSTZ"  : ""
    },
    "Africa/Lubumbashi": {
        "STZ"   : "Central Africa Time",
        "DSTZ"  : ""
    },
    "Africa/Lusaka": {
        "STZ"   : "Central Africa Time",
        "DSTZ"  : ""
    },
    "Africa/Malabo": {
        "STZ"   : "West Africa Time",
        "DSTZ"  : ""
    },
    "Africa/Maputo": {
        "STZ"   : "Central Africa Time",
        "DSTZ"  : ""
    },
    "Africa/Maseru": {
        "STZ"   : "South African Standard Time",
        "DSTZ"  : ""
    },
    "Africa/Mbabane": {
        "STZ"   : "South African Standard Time",
        "DSTZ"  : ""
    },
    "Africa/Mogadishu": {
        "STZ"   : "Eastern Africa Time",
        "DSTZ"  : ""
    },
    "Africa/Monrovia": {
        "STZ"   : "Greenwich Mean Time",
        "DSTZ"  : ""
    },
    "Africa/Nairobi": {
        "STZ"   : "Eastern Africa Time",
        "DSTZ"  : ""
    },
    "Africa/Ndjamena": {
        "STZ"   : "West Africa Time",
        "DSTZ"  : ""
    },
    "Africa/Niamey": {
        "STZ"   : "West Africa Time",
        "DSTZ"  : ""
    },
    "Africa/Nouakchott": {
        "STZ"   : "Greenwich Mean Time",
        "DSTZ"  : ""
    },
    "Africa/Ouagadougou": {
        "STZ"   : "Greenwich Mean Time",
        "DSTZ"  : ""
    },
    "Africa/Porto-Novo": {
        "STZ"   : "West Africa Time",
        "DSTZ"  : ""
    },
    "Africa/Sao_Tome": {
        "STZ"   : "Greenwich Mean Time",
        "DSTZ"  : ""
    },
    "Africa/Tripoli": {
        "STZ"   : "Eastern Africa Time",
        "DSTZ"  : ""
    },
    "Africa/Tunis": {
        "STZ"   : "Central European Time",
        "DSTZ"  : ""
    },
    "Africa/Windhoek": {
        "STZ"   : "Central Africa Time",
        "DSTZ"  : ""
    },
    "America/Adak": {
        "STZ"   : "Hawaii–Aleutian Standard Time",
        "DSTZ"  : "Hawaii–Aleutian Daylight Time"
    },
    "America/Anchorage": {
        "STZ"   : "Alaska Standard Time",
        "DSTZ"  : "Alaska Daylight Time"
    },
    "America/Anguilla": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : ""
    },
    "America/Antigua": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : ""
    },
    "America/Araguaina": {
        "STZ"   : "Brasília Time",
        "DSTZ"  : ""
    },
    "America/Argentina/Buenos_Aires": {
        "STZ"   : "Argentina Time",
        "DSTZ"  : ""
    },
    "America/Argentina/Catamarca": {
        "STZ"   : "Argentina Time",
        "DSTZ"  : ""
    },
    "America/Argentina/Cordoba": {
        "STZ"   : "Argentina Time",
        "DSTZ"  : ""
    },
    "America/Argentina/Jujuy": {
        "STZ"   : "Argentina Time",
        "DSTZ"  : ""
    },
    "America/Argentina/La_Rioja": {
        "STZ"   : "Argentina Time",
        "DSTZ"  : ""
    },
    "America/Argentina/Mendoza": {
        "STZ"   : "Argentina Time",
        "DSTZ"  : ""
    },
    "America/Argentina/Rio_Gallegos": {
        "STZ"   : "Argentina Time",
        "DSTZ"  : ""
    },
    "America/Argentina/Salta": {
        "STZ"   : "Argentina Time",
        "DSTZ"  : ""
    },
    "America/Argentina/San_Juan": {
        "STZ"   : "Argentina Time",
        "DSTZ"  : ""
    },
    "America/Argentina/San_Luis": {
        "STZ"   : "Argentina Time",
        "DSTZ"  : ""
    },
    "America/Argentina/Tucuman": {
        "STZ"   : "Argentina Time",
        "DSTZ"  : ""
    },
    "America/Argentina/Ushuaia": {
        "STZ"   : "Argentina Time",
        "DSTZ"  : ""
    },
    "America/Aruba": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : ""
    },
    "America/Asuncion": {
        "STZ"   : "Paraguay Time",
        "DSTZ"  : "Paraguay Summer Time"
    },
    "America/Atikokan": {
        "STZ"   : "Eastern Standard Time",
        "DSTZ"  : ""
    },
    "America/Bahia": {
        "STZ"   : "Brasília Time",
        "DSTZ"  : ""
    },
    "America/Bahia_Banderas": {
        "STZ":  "Central Standard Time",
        "DSTZ": "Central Daylight Time"
    },
    "America/Barbados": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : ""
    },
    "America/Belem": {
        "STZ"   : "Brasília Time",
        "DSTZ"  : ""
    },
    "America/Belize": {
        "STZ"   : "Central Standard Time",
        "DSTZ"  : ""
    },
    "America/Blanc-Sablon": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : ""
    },
    "America/Boa_Vista": {
        "STZ"   : "Amazon Time",
        "DSTZ"  : ""
    },
    "America/Bogota": {
        "STZ"   : "Colombia Time",
        "DSTZ"  : ""
    },
    "America/Boise": {
        "STZ"   : "Mountain Standard Time",
        "DSTZ"  : "Mountain Daylight Time"
    },
    "America/Cambridge_Bay": {
        "STZ"   : "Mountain Standard Time",
        "DSTZ"  : "Mountain Daylight Time"
    },
    "America/Campo_Grande": {
        "STZ"   : "Amazon Time",
        "DSTZ"  : ""
    },
    "America/Cancun": {
        "STZ"   : "Eastern Standard Time",
        "DSTZ"  : ""
    },
    "America/Caracas": {
        "STZ"   : "Venezuelan Standard Time",
        "DSTZ"  : ""
    },
    "America/Cayenne": {
        "STZ"   : "French Guiana Time",
        "DSTZ"  : ""
    },
    "America/Cayman": {
        "STZ"   : "Eastern Standard Time",
        "DSTZ"  : ""
    },
    "America/Chicago": {
        "STZ"   : "Central Standard Time",
        "DSTZ"  : "Central Daylight Time"
    },
    "America/Chihuahua": {
        "STZ":  "Mountain Standard Time",
        "DSTZ": "Mountain Daylight Time"
    },
    "America/Costa_Rica": {
        "STZ"   : "Central Standard Time",
        "DSTZ"  : ""
    },
    "America/Creston": {
        "STZ"   : "Central Standard Time",
        "DSTZ"  : ""
    },
    "America/Cuiaba": {
        "STZ"   : "Brasília Time",
        "DSTZ"  : ""
    },
    "America/Curacao": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : ""
    },
    "America/Danmarkshavn": {
        "STZ"   : "Greenwich Mean Time",
        "DSTZ"  : ""
    },
    "America/Dawson": {
        "STZ"   : "Mountain Standard Time",
        "DSTZ"  : ""
    },
    "America/Dawson_Creek": {
        "STZ"   : "Mountain Standard Time",
        "DSTZ"  : ""
    },
    "America/Denver": {
        "STZ"   : "Mountain Standard Time",
        "DSTZ"  : "Mountain Daylight Time"
    },
    "America/Detroit": {
        "STZ"   : "Eastern Standard Time",
        "DSTZ"  : "Eastern Daylight Time"
    },"America/Dominica": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : ""
    },
    "America/Edmonton": {
        "STZ"   : "Mountain Standard Time",
        "DSTZ"  : "Mountain Daylight Time"
    },
    "America/Eirunepe": {
        "STZ"   : "Acre Time",
        "DSTZ"  : ""
    },
    "America/El_Salvador": {
        "STZ"   : "Central Standard Time",
        "DSTZ"  : ""
    },
    "America/Fort_Nelson": {
        "STZ"   : "Mountain Standard Time",
        "DSTZ"  : ""
    },
    "America/Fortaleza": {
        "STZ"   : "Brasília Time",
        "DSTZ"  : ""
    },
    "America/Glace_Bay": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : "Atlantic Daylight Time"
    },
    "America/Goose_Bay": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : "Atlantic Daylight Time"
    },
    "America/Grand_Turk": {
        "STZ"   : "Eastern Standard Time",
        "DSTZ"  : "Eastern Daylight Time"
    },
    "America/Grenada": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : ""
    },
    "America/Guadeloupe": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : ""
    },
    "America/Guatemala": {
        "STZ"   : "Central Standard Time",
        "DSTZ"  : ""
    },
    "America/Guayaquil": {
        "STZ"   : "Ecuador Time",
        "DSTZ"  : ""
    },
    "America/Guyana": {
        "STZ"   : "Guyana Time",
        "DSTZ"  : ""
    },
    "America/Halifax": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : "Atlantic Daylight Time"
    },
    "America/Havana": {
        "STZ"   : "Cuba Standard Time",
        "DSTZ"  : "Cuba Daylight Time"
    },
    "America/Hermosillo": {
        "STZ":  "Mountain Standard Time",
        "DSTZ": ""
    },
    "America/Indiana/Indianapolis": {
        "STZ"   : "Eastern Standard Time",
        "DSTZ"  : "Eastern Daylight Time"
    },
    "America/Indiana/Knox": {
        "STZ"   : "Central Standard Time",
        "DSTZ"  : "Central Daylight Time"
    },
    "America/Indiana/Marengo": {
        "STZ"   : "Eastern Standard Time",
        "DSTZ"  : "Eastern Daylight Time"
    },
    "America/Indiana/Petersburg": {
        "STZ"   : "Eastern Standard Time",
        "DSTZ"  : "Eastern Daylight Time"
    },
    "America/Indiana/Tell_City": {
        "STZ"   : "Central Standard Time",
        "DSTZ"  : "Central Daylight Time"
    },
    "America/Indiana/Vevay": {
        "STZ"   : "Central Standard Time",
        "DSTZ"  : "Central Daylight Time"
    },
    "America/Indiana/Vincennes": {
        "STZ"   : "Eastern Standard Time",
        "DSTZ"  : "Eastern Daylight Time"
    },
    "America/Indiana/Winamac": {
        "STZ"   : "Eastern Standard Time",
        "DSTZ"  : "Eastern Daylight Time"
    },
           "America/Inuvik": {
        "STZ"   : "Mountain Standard Time",
        "DSTZ"  : "Mountain Daylight Time"
    },
    "America/Iqaluit": {
        "STZ"   : "Eastern Standard Time",
        "DSTZ"  : "Eastern Daylight Time"
    },
    "America/Jamaica": {
        "STZ"   : "Eastern Standard Time",
        "DSTZ"  : ""
    },
    "America/Juneau": {
        "STZ"   : "Alaska Standard Time",
        "DSTZ"  : "Alaska Daylight Time"
    },
    "America/Kentucky/Louisville": {
        "STZ"   : "Eastern Standard Time",
        "DSTZ"  : "Eastern Daylight Time"
    },
    "America/Kentucky/Monticello": {
        "STZ"   : "Eastern Standard Time",
        "DSTZ"  : "Eastern Daylight Time"
    },
    "America/Kralendijk": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : ""
    },
    "America/La_Paz": {
        "STZ"   : "Bolivia Time",
        "DSTZ"  : ""
    },
    "America/Lima": {
        "STZ"   : "Peru Time",
        "DSTZ"  : ""
    },
    "America/Los_Angeles": {
        "STZ"   : "Pacific Standard Time",
        "DSTZ"  : "Pacific Daylight Time"
    },
    "America/Lower_Princes": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : ""
    },
    "America/Maceio": {
        "STZ"   : "Brasília Time",
        "DSTZ"  : ""
    },
    "America/Managua": {
        "STZ"   : "Central Standard Time",
        "DSTZ"  : ""
    },
    "America/Manaus": {
        "STZ"   : "Amazon Time",
        "DSTZ"  : ""
    },
    "America/Marigot": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : ""
    },
    "America/Martinique": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : ""
    },
    "America/Matamoros": {
        "STZ":  "Central Standard Time",
        "DSTZ": "Central Daylight Time"
    },
    "America/Mazatlan": {
        "STZ":  "Mountain Standard Time",
        "DSTZ": "Mountain Daylight Time"
    },
    "America/Menominee": {
        "STZ"   : "Central Standard Time",
        "DSTZ"  : "Central Daylight Time"
    },
    "America/Merida": {
        "STZ":  "Central Standard Time",
        "DSTZ": "Central Daylight Time"
    },
    "America/Metlakatla": {
        "STZ"   : "Alaska Standard Time",
        "DSTZ"  : "Alaska Daylight Time"
    },
    "America/Mexico_City": {
        "STZ":  "Central Standard Time",
        "DSTZ": "Central Daylight Time"
    },
    "America/Miquelon": {
        "STZ"   : "Saint Pierre and Miquelon Standard Time",
        "DSTZ"  : "Saint Pierre and Miquelon Daylight Time"
    },
    "America/Moncton": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : "Atlantic Daylight Time"
    },
    "America/Monterrey": {
        "STZ":  "Central Standard Time",
        "DSTZ": "Central Daylight Time"
    },
    "America/Montevideo": {
        "STZ"   : "Uruguay Time",
        "DSTZ"  : ""
    },
    "America/Montserrat": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : ""
    },
    "America/Nassau": {
        "STZ"   : "Eastern Standard Time",
        "DSTZ"  : "Eastern Daylight Time"
    },
    "America/New_York": {
        "STZ"   : "Eastern Standard Time",
        "DSTZ"  : "Eastern Daylight Time"
    },
    "America/Nipigon": {
        "STZ"   : "Eastern Standard Time",
        "DSTZ"  : "Eastern Daylight Time"
    },
    "America/Nome": {
        "STZ"   : "Alaska Standard Time",
        "DSTZ"  : "Alaska Daylight Time"
    },
    "America/Noronha": {
        "STZ"   : "Fernando de Noronha Time",
        "DSTZ"  : ""
    },
    "America/North_Dakota/Beulah": {
        "STZ"   : "Central Standard Time",
        "DSTZ"  : "Central Daylight Time"
    },
    "America/North_Dakota/Center": {
        "STZ"   : "Central Standard Time",
        "DSTZ"  : "Central Daylight Time"
    },
    "America/North_Dakota/New_Salem": {
        "STZ"   : "Central Standard Time",
        "DSTZ"  : "Central Daylight Time"
    },
    "America/Nuuk": {
        "STZ"   : "West Greenland Time",
        "DSTZ"  : "West Greenland Summer Time"
    },
    "America/Ojinaga": {
        "STZ":  "Mountain Standard Time",
        "DSTZ": "Mountain Daylight Time"
    },
    "America/Panama": {
        "STZ"   : "Eastern Standard Time",
        "DSTZ"  : ""
    },
    "America/Pangnirtung": {
        "STZ"   : "Eastern Standard Time",
        "DSTZ"  : "Eastern Daylight Time"
    },
    "America/Paramaribo": {
        "STZ"   : "Suriname Time",
        "DSTZ"  : ""
    },
    "America/Phoenix": {
        "STZ"   : "Mountain Standard Time",
        "DSTZ"  : ""
    },
    "America/Port-au-Prince": {
        "STZ"   : "Eastern Standard Time",
        "DSTZ"  : "Eastern Daylight Time"
    },
    "America/Port_of_Spain": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : ""
    },
    "America/Porto_Velho": {
        "STZ"   : "Amazon Time",
        "DSTZ"  : ""
    },
    "America/Puerto_Rico": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : ""
    },
    "America/Punta_Arenas": {
        "STZ"   : "Chile Summer Time",
        "DSTZ"  : ""
    },
    "America/Rainy_River": {
        "STZ"   : "Central Standard Time",
        "DSTZ"  : "Central Daylight Time"
    },
    "America/Rankin_Inlet": {
        "STZ"   : "Central Standard Time",
        "DSTZ"  : "Central Daylight Time"
    },
    "America/Recife": {
        "STZ"   : "Brasília Time",
        "DSTZ"  : ""
    },
    "America/Regina": {
        "STZ"   : "Central Standard Time",
        "DSTZ"  : ""
    },
    "America/Resolute": {
        "STZ"   : "Central Standard Time",
        "DSTZ"  : "Central Daylight Time"
    },
    "America/Rio_Branco": {
        "STZ"   : "Acre Time",
        "DSTZ"  : ""
    },
    "America/Santarem": {
        "STZ"   : "Brasília Time",
        "DSTZ"  : ""
    },
    "America/Santiago": {
        "STZ"   : "Chile Standard Time",
        "DSTZ"  : "Chile Summer Time"
    },
    "America/Santo_Domingo": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : ""
    },
    "America/Sao_Paulo": {
        "STZ"   : "Brasília Time",
        "DSTZ"  : ""
    },
    "America/Scoresbysund": {
        "STZ"   : "Eastern Greenland Time",
        "DSTZ"  : "Eastern Greenland Summer Time"
    },
    "America/Sitka": {
        "STZ"   : "Alaska Standard Time",
        "DSTZ"  : "Alaska Daylight Time"
    },
    "America/St_Barthelemy": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : ""
    },
    "America/St_Johns": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : ""
    },
    "America/St_Kitts": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : ""
    },
    "America/St_Lucia": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : ""
    },
    "America/St_Thomas": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : ""
    },
    "America/St_Vincent": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : ""
    },
    "America/Swift_Current": {
        "STZ"   : "Central Standard Time",
        "DSTZ"  : ""
    },
    "America/Tegucigalpa": {
        "STZ"   : "Central Standard Time",
        "DSTZ"  : ""
    },
    "America/Thule": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : "Atlantic Daylight Time"
    },
    "America/Thunder_Bay": {
        "STZ"   : "Eastern Standard Time",
        "DSTZ"  : "Eastern Daylight Time"
    },
    "America/Tijuana": {
        "STZ":  "Pacific Standard Time",
        "DSTZ": "Pacific Daylight Time"
    },
    "America/Toronto": {
        "STZ"   : "Eastern Standard Time",
        "DSTZ"  : "Eastern Daylight Time"
    },
    "America/Tortola": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : ""
    },
    "America/Vancouver": {
        "STZ"   : "Pacific Standard Time",
        "DSTZ"  : "Pacific Daylight Time"
    },
    "America/Whitehorse": {
        "STZ"   : "Mountain Standard Time",
        "DSTZ"  : ""
    },
    "America/Winnipeg": {
        "STZ"   : "Central Standard Time",
        "DSTZ"  : "Central Daylight Time"
    },
    "America/Yakutat": {
        "STZ"   : "Alaska Standard Time",
        "DSTZ"  : "Alaska Daylight Time"
    },
    "America/Yellowknife": {
        "STZ"   : "Mountain Standard Time",
        "DSTZ"  : "Mountain Daylight Time"
    },
    "Antarctica/Casey": {
        "STZ"   : "Casey Time",
        "DSTZ"  : "Casey Summer Time"
    },
    "Antarctica/Davis": {
        "STZ"   : "Davis Time",
        "DSTZ"  : ""
    },
    "Antarctica/DumontDUrville": {
        "STZ"   : "Dumont d'Urville Time",
        "DSTZ"  : ""
    },
    "Antarctica/Macquarie": {
        "STZ"   : "Macquarie Island Station Time",
        "DSTZ"  : ""
    },
    "Antarctica/Mawson": {
        "STZ"   : "Mawson Station Time",
        "DSTZ"  : ""
    },
    "Antarctica/McMurdo": {
        "STZ"   : "New Zealand Standard Time",
        "DSTZ"  : "New Zealand Daylight Time"
    },
    "Antarctica/Palmer": {
        "STZ"   : "Chile Summer Time",
        "DSTZ"  : ""
    },
    "Antarctica/Rothera": {
        "STZ"   : "Brasília Time",
        "DSTZ"  : ""
    },
    "Antarctica/Syowa": {
        "STZ"   : "Showa Station Time",
        "DSTZ"  : ""
    },
    "Antarctica/Troll": {
        "STZ"   : "Greenwich Mean Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Antarctica/Vostok": {
        "STZ"   : "Vostok Station Time",
        "DSTZ"  : ""
    },
    "Arctic/Longyearbyen": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Asia/Aden": {
        "STZ"   : "Arabia Standard Time",
        "DSTZ"  : ""
    },
    "Asia/Almaty": {
        "STZ"   : "Alma-Ata Time",
        "DSTZ"  : ""
    },
    "Asia/Amman": {
        "STZ"   : "Eastern European Time",
        "DSTZ"  : "Eastern European Summer Time"
    },
    "Asia/Anadyr": {
        "STZ"   : "Anadyr Time",
        "DSTZ"  : ""
    },
    "Asia/Aqtau": {
        "STZ"   : "Alma-Ata Time",
        "DSTZ"  : ""
    },
    "Asia/Aqtobe": {
        "STZ"   : "Aqtobe Time",
        "DSTZ"  : ""
    },
    "Asia/Ashgabat": {
        "STZ"   : "Turkmenistan Time",
        "DSTZ"  : ""
    },
    "Asia/Baghdad": {
        "STZ"   : "Arabia Standard Time",
        "DSTZ"  : ""
    },
    "Asia/Bahrain": {
        "STZ"   : "Arabia Standard Time",
        "DSTZ"  : ""
    },
    "Asia/Baku": {
        "STZ"   : "Azerbaijan Time",
        "DSTZ"  : ""
    },
    "Asia/Bangkok": {
        "STZ"   : "Indochina Time",
        "DSTZ"  : ""
    },
    "Asia/Barnaul": {
        "STZ"   : "MSK+4",
        "DSTZ"  : ""
    },
    "Asia/Beirut": {
        "STZ"   : "Eastern European Time",
        "DSTZ"  : "Eastern European Summer Time"
    },
    "Asia/Bishkek": {
        "STZ"   : "Kyrgyzstan Time",
        "DSTZ"  : ""
    },
    "Asia/Brunei": {
        "STZ"   : "Brunei Darussalam Time",
        "DSTZ"  : ""
    },
    "Asia/Chita": {
        "STZ"   : "Yakutsk Time",
        "DSTZ"  : ""
    },
    "Asia/Choibalsan": {
        "STZ"   : "Choibalsan Standard Time",
        "DSTZ"  : ""
    },
    "Asia/Colombo": {
        "STZ"   : "Sri Lanka Standard Time",
        "DSTZ"  : ""
    },
    "Asia/Damascus": {
        "STZ"   : "Eastern European Time",
        "DSTZ"  : "Eastern European Summer Time"
    },
    "Asia/Dhaka": {
        "STZ"   : "Bangladesh Standard Time",
        "DSTZ"  : ""
    },
    "Asia/Dili": {
        "STZ"   : "Timor Leste Time",
        "DSTZ"  : ""
    },
    "Asia/Dubai": {
        "STZ"   : "Gulf Standard Time",
        "DSTZ"  : ""
    },
    "Asia/Dushanbe": {
        "STZ"   : "Tajikistan Time",
        "DSTZ"  : ""
    },
    "Asia/Famagusta": {
        "STZ"   : "Eastern European Time",
        "DSTZ"  : "Eastern European Summer Time"
    },
    "Asia/Gaza": {
        "STZ"   : "Eastern European Time",
        "DSTZ"  : ""
    },
    "Asia/Hebron": {
        "STZ"   : "Eastern European Time",
        "DSTZ"  : "Eastern European Summer Time"
    },
    "Asia/Ho_Chi_Minh": {
        "STZ"   : "Indochina Time",
        "DSTZ"  : ""
    },
    "Asia/Hong_Kong": {
        "STZ"   : "Hong Kong Time",
        "DSTZ"  : ""
    },
    "Asia/Hovd": {
        "STZ"   : "Hovd Time",
        "DSTZ"  : ""
    },
    "Asia/Irkutsk": {
        "STZ"   : "Irkutsk Time",
        "DSTZ"  : ""
    },
    "Asia/Jakarta": {
        "STZ"   : "Western Indonesian Time",
        "DSTZ"  : ""
    },
    "Asia/Jayapura": {
        "STZ"   : "Western Indonesian Time",
        "DSTZ"  : ""
    },
    "Asia/Jerusalem": {
        "STZ"   : "Israel Standard Time",
        "DSTZ"  : "Israel Daylight Time"
    },
    "Asia/Kabul": {
        "STZ"   : "Afghanistan Time",
        "DSTZ"  : ""
    },
    "Asia/Kamchatka": {
        "STZ"   : "Kamchatka Time",
        "DSTZ"  : ""
    },
    "Asia/Karachi": {
        "STZ"   : "Pakistan Standard Time",
        "DSTZ"  : ""
    },
    "Asia/Kathmandu": {
        "STZ"   : "Nepal Time",
        "DSTZ"  : ""
    },
    "Asia/Khandyga": {
        "STZ"   : "Yakutsk Time",
        "DSTZ"  : ""
    },
    "Asia/Kolkata": {
        "STZ"   : "India Standard Time",
        "DSTZ"  : ""
    },
    "Asia/Krasnoyarsk": {
        "STZ"   : "Krasnoyarsk Time",
        "DSTZ"  : ""
    },
    "Asia/Kuala_Lumpur": {
        "STZ"   : "Malaysia Time",
        "DSTZ"  : ""
    },
    "Asia/Kuching": {
        "STZ"   : "Malaysia Time",
        "DSTZ"  : ""
    },
    "Asia/Kuwait": {
        "STZ"   : "Arabia Standard Time",
        "DSTZ"  : ""
    },
    "Asia/Macau": {
        "STZ"   : "China Standard Time",
        "DSTZ"  : ""
    },
    "Asia/Magadan": {
        "STZ"   : "Magadan Time",
        "DSTZ"  : ""
    },
    "Asia/Makassar": {
        "STZ"   : "Central Indonesia Time",
        "DSTZ"  : ""
    },
    "Asia/Manila": {
        "STZ"   : "Philippine Time",
        "DSTZ"  : ""
    },
    "Asia/Muscat": {
        "STZ"   : "Gulf Standard Time",
        "DSTZ"  : ""
    },
    "Asia/Nicosia": {
        "STZ"   : "Eastern European Time",
        "DSTZ"  : "Eastern European Summer Time"
    },
    "Asia/Novokuznetsk": {
        "STZ"   : "Krasnoyarsk Time",
        "DSTZ"  : ""
    },
    "Asia/Novosibirsk": {
        "STZ"   : "Novosibirsk Time",
        "DSTZ"  : ""
    },
    "Asia/Omsk": {
        "STZ"   : "Omsk Time",
        "DSTZ"  : ""
    },
    "Asia/Oral": {
        "STZ"   : "Oral Time",
        "DSTZ"  : ""
    },
    "Asia/Phnom_Penh": {
        "STZ"   : "Indochina Time",
        "DSTZ"  : ""
    },
    "Asia/Pontianak": {
        "STZ"   : "Western Indonesian Time",
        "DSTZ"  : ""
    },
    "Asia/Pyongyang": {
        "STZ"   : "Korea Standard Time",
        "DSTZ"  : ""
    },
    "Asia/Qatar": {
        "STZ"   : "Arabia Standard Time",
        "DSTZ"  : ""
    },
    "Asia/Qostanay": {
        "STZ"   : "Alma-Ata Time",
        "DSTZ"  : ""
    },
    "Asia/Qyzylorda": {
        "STZ"   : "MSK+2",
        "DSTZ"  : ""
    },
    "Asia/Riyadh": {
        "STZ"   : "Arabia Standard Time",
        "DSTZ"  : ""
    },
    "Asia/Sakhalin": {
        "STZ"   : "Sakhalin Island Time",
        "DSTZ"  : ""
    },
    "Asia/Samarkand": {
        "STZ"   : "Uzbekistan Time",
        "DSTZ"  : ""
    },
    "Asia/Seoul": {
        "STZ"   : "Korea Standard Time",
        "DSTZ"  : ""
    },
    "Asia/Shanghai": {
        "STZ"   : "China Standard Time",
        "DSTZ"  : ""
    },
    "Asia/Singapore": {
        "STZ"   : "Singapore Time",
        "DSTZ"  : ""
    },
    "Asia/Srednekolymsk": {
        "STZ"   : "Srednekolymsk Time",
        "DSTZ"  : ""
    },
    "Asia/Taipei": {
        "STZ"   : "China Standard Time",
        "DSTZ"  : ""
    },
    "Asia/Tashkent": {
        "STZ"   : "Uzbekistan Time",
        "DSTZ"  : ""
    },
    "Asia/Tbilisi": {
        "STZ"   : "Georgia Standard Time",
        "DSTZ"  : ""
    },
    "Asia/Tehran": {
        "STZ"   : "Iran Standard Time",
        "DSTZ"  : "Iran Daylight Time"
    },
    "Asia/Thimphu": {
        "STZ"   : "Bhutan Time",
        "DSTZ"  : ""
    },
    "Asia/Tokyo": {
        "STZ"   : "Japan Standard Time",
        "DSTZ"  : ""
    },
    "Asia/Tomsk": {
        "STZ"   : "MSK+4",
        "DSTZ"  : ""
    },
    "Asia/Ulaanbaatar": {
        "STZ"   : "Ulaanbaatar Standard Time",
        "DSTZ"  : ""
    },
    "Asia/Urumqi": {
        "STZ"   : "China Standard Time",
        "DSTZ"  : ""
    },
    "Asia/Ust-Nera": {
        "STZ"   : "Vladivostok Time",
        "DSTZ"  : ""
    },
    "Asia/Vientiane": {
        "STZ"   : "Indochina Time",
        "DSTZ"  : ""
    },
    "Asia/Vladivostok": {
        "STZ"   : "Vladivostok Time",
        "DSTZ"  : ""
    },
    "Asia/Yakutsk": {
        "STZ"   : "Yakutsk Time",
        "DSTZ"  : ""
    },
    "Asia/Yangon": {
        "STZ"   : "Myanmar Standard Time",
        "DSTZ"  : ""
    },
    "Asia/Yekaterinburg": {
        "STZ"   : "Yekaterinburg Time",
        "DSTZ"  : ""
    },
    "Asia/Yerevan": {
        "STZ"   : "Armenia Time",
        "DSTZ"  : ""
    },
    "Atlantic/Azores": {
        "STZ"   : "Azores Standard Time",
        "DSTZ"  : "Azores Summer Time"
    },
    "Atlantic/Bermuda": {
        "STZ"   : "Atlantic Standard Time",
        "DSTZ"  : "Atlantic Daylight Time"
    },
    "Atlantic/Canary": {
        "STZ"   : "Western European Time",
        "DSTZ"  : "Western European Summer Time"
    },
    "Atlantic/Cape_Verde": {
        "STZ"   : "Cape Verde Time",
        "DSTZ"  : ""
    },
    "Atlantic/Faroe": {
        "STZ"   : "Western European Time",
        "DSTZ"  : "Western European Summer Time"
    },
    "Atlantic/Madeira": {
        "STZ"   : "Western European Time",
        "DSTZ"  : "Western European Summer Time"
    },
    "Atlantic/Reykjavik": {
        "STZ"   : "Greenwich Mean Time",
        "DSTZ"  : ""
    },
    "Atlantic/South_Georgia": {
        "STZ"   : "South Georgia and the South Sandwich Islands Time",
        "DSTZ"  : ""
    },
    "Atlantic/St_Helena": {
        "STZ"   : "Greenwich Mean Time",
        "DSTZ"  : ""
    },
    "Atlantic/Stanley": {
        "STZ"   : "Falkland Islands Summer Time",
        "DSTZ"  : ""
    },
    "Australia/Adelaide": {
        "STZ"   : "Australian Central Standard Time",
        "DSTZ"  : "Australian Central Daylight Time"
    },
    "Australia/Brisbane": {
        "STZ"   : "Australian Eastern Standard Time",
        "DSTZ"  : ""
    },
    "Australia/Broken_Hill": {
        "STZ"   : "Australian Central Standard Time",
        "DSTZ"  : "Australian Central Daylight Time"
    },
    "Australia/Darwin": {
        "STZ"   : "Australian Central Standard Time",
        "DSTZ"  : ""
    },
    "Australia/Eucla": {
        "STZ"   : "Australian Western Standard Time",
        "DSTZ"  : ""
    },
    "Australia/Hobart": {
        "STZ"   : "Australian Eastern Standard Time",
        "DSTZ"  : "Australian Eastern Daylight Time"
    },
    "Australia/Lindeman": {
        "STZ"   : "Australian Eastern Standard Time",
        "DSTZ"  : ""
    },
    "Australia/Lord_Howe": {
        "STZ"   : "Lord Howe Standard Time",
        "DSTZ"  : "Lord Howe Daylight Time"
    },
    "Australia/Melbourne": {
        "STZ"   : "Australian Eastern Standard Time",
        "DSTZ"  : "Australian Eastern Daylight Time"
    },
    "Australia/Perth": {
        "STZ"   : "Australian Western Standard Time",
        "DSTZ"  : ""
    },
    "Australia/Sydney": {
        "STZ"   : "Australian Eastern Standard Time",
        "DSTZ"  : "Australian Eastern Daylight Time"
    },
    "Europe/Amsterdam": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Europe/Andorra": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Europe/Astrakhan": {
        "STZ"   : "MSK+1",
        "DSTZ"  : ""
    },
    "Europe/Athens": {
        "STZ"   : "Eastern European Time",
        "DSTZ"  : "Eastern European Summer Time"
    },
    "Europe/Belgrade": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Europe/Berlin": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Europe/Bratislava": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Europe/Brussels": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Europe/Bucharest": {
        "STZ"   : "Eastern European Time",
        "DSTZ"  : "Eastern European Summer Time"
    },
    "Europe/Budapest": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Europe/Busingen": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Europe/Chisinau": {
        "STZ"   : "Eastern European Time",
        "DSTZ"  : "Eastern European Summer Time"
    },
    "Europe/Copenhagen": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Europe/Dublin": {
        "STZ"   : "Greenwich Mean Time",
        "DSTZ"  : "Irish Standard Time"
    },
    "Europe/Gibraltar": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Europe/Guernsey": {
        "STZ"   : "Greenwich Mean Time",
        "DSTZ"  : "British Summer Time"
    },
    "Europe/Helsinki": {
        "STZ"   : "Eastern European Time",
        "DSTZ"  : "Eastern European Summer Time"
    },
    "Europe/Isle_of_Man": {
        "STZ"   : "Greenwich Mean Time",
        "DSTZ"  : "British Summer Time"
    },
    "Europe/Istanbul": {
        "STZ"   : "Turkey Time",
        "DSTZ"  : ""
    },
    "Europe/Jersey": {
        "STZ"   : "Greenwich Mean Time",
        "DSTZ"  : "British Summer Time"
    },
    "Europe/Kaliningrad": {
        "STZ"   : "Eastern European Time",
        "DSTZ"  : ""
    },
    "Europe/Kiev": {
        "STZ"   : "Eastern European Time",
        "DSTZ"  : "Eastern European Summer Time"
    },
    "Europe/Kirov": {
        "STZ"   : "Moscow Time",
        "DSTZ"  : ""
    },
    "Europe/Lisbon": {
        "STZ"   : "Western European Time",
        "DSTZ"  : "Western European Summer Time"
    },
    "Europe/Ljubljana": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Europe/London": {
        "STZ"   : "Greenwich Mean Time",
        "DSTZ"  : "British Summer Time"
    },
    "Europe/Luxembourg": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Europe/Madrid": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Europe/Malta": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Europe/Mariehamn": {
        "STZ"   : "Eastern European Time",
        "DSTZ"  : "Eastern European Summer Time"
    },
    "Europe/Minsk": {
        "STZ"   : "Moscow Time",
        "DSTZ"  : ""
    },
    "Europe/Monaco": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Europe/Moscow": {
        "STZ"   : "Moscow Time",
        "DSTZ"  : ""
    },
    "Europe/Oslo": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Europe/Paris": {
        "STZ": "Central European Time",
        "DSTZ": "Central European Summer Time"
    },
    "Europe/Podgorica": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Europe/Prague": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Europe/Riga": {
        "STZ"   : "Eastern European Time",
        "DSTZ"  : "Eastern European Summer Time"
    },
    "Europe/Rome": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Europe/Samara": {
        "STZ"   : "Samara Time",
        "DSTZ"  : ""
    },
    "Europe/San_Marino": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Europe/Sarajevo": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Europe/Saratov": {
        "STZ"   : "MSK+1",
        "DSTZ"  : ""
    },
    "Europe/Simferopol": {
        "STZ"   : "Moscow Time",
        "DSTZ"  : ""
    },
    "Europe/Skopje": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Europe/Sofia": {
        "STZ"   : "Eastern European Time",
        "DSTZ"  : "Eastern European Summer Time"
    },
    "Europe/Stockholm": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Europe/Tallinn": {
        "STZ"   : "Eastern European Time",
        "DSTZ"  : "Eastern European Summer Time"
    },
    "Europe/Tirane": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Europe/Ulyanovsk": {
        "STZ"   : "MSK+1",
        "DSTZ"  : ""
    },
    "Europe/Uzhgorod": {
        "STZ"   : "Eastern European Time",
        "DSTZ"  : "Eastern European Summer Time"
    },
    "Europe/Vaduz": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Europe/Vatican": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Europe/Vienna": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Europe/Vilnius": {
        "STZ"   : "Eastern European Time",
        "DSTZ"  : "Eastern European Summer Time"
    },
    "Europe/Volgograd": {
        "STZ"   : "Moscow Time",
        "DSTZ"  : ""
    },
    "Europe/Warsaw": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Europe/Zagreb": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Europe/Zaporozhye": {
        "STZ"   : "Eastern European Time",
        "DSTZ"  : "Eastern European Summer Time"
    },
    "Europe/Zurich": {
        "STZ"   : "Central European Time",
        "DSTZ"  : "Central European Summer Time"
    },
    "Indian/Antananarivo": {
        "STZ"   : "Eastern Africa Time",
        "DSTZ"  : ""
    },
    "Indian/Chagos": {
        "STZ"   : "Indian Chagos Time",
        "DSTZ"  : ""
    },
    "Indian/Christmas": {
        "STZ"   : "Christmas Island Time",
        "DSTZ"  : ""
    },
    "Indian/Cocos": {
        "STZ"   : "Cocos Islands Time",
        "DSTZ"  : ""
    },
    "Indian/Comoro": {
        "STZ"   : "Eastern Africa Time",
        "DSTZ"  : ""
    },
    "Indian/Kerguelen": {
        "STZ"   : "French Southern and Antarctic Time",
        "DSTZ"  : ""
    },
    "Indian/Mahe": {
        "STZ"   : "Seychelles Time",
        "DSTZ"  : ""
    },
    "Indian/Maldives": {
        "STZ"   : "Maldives Time",
        "DSTZ"  : ""
    },
    "Indian/Mauritius": {
        "STZ"   : "Mauritius Time",
        "DSTZ"  : ""
    },
    "Indian/Mayotte": {
        "STZ"   : "Eastern Africa Time",
        "DSTZ"  : ""
    },
    "Indian/Reunion": {
        "STZ"   : "Réunion Time",
        "DSTZ"  : ""
    },
    "Pacific/Apia": {
        "STZ"   : "West Samoa Time",
        "DSTZ"  : "West Samoa Summer Time"
    },
    "Pacific/Auckland": {
        "STZ"   : "New Zealand Standard Time",
        "DSTZ"  : "New Zealand Daylight Time"
    },
    "Pacific/Bougainville": {
        "STZ"   : "Bougainville Standard Time",
        "DSTZ"  : ""
    },
    "Pacific/Chatham": {
        "STZ"   : "Chatham Island Standard Time",
        "DSTZ"  : "Chatham Island Daylight Time"
    },
    "Pacific/Chuuk": {
        "STZ"   : "Chuuk Time",
        "DSTZ"  : ""
    },
    "Pacific/Easter": {
        "STZ"   : "Easter Island Standard Time",
        "DSTZ"  : "Easter Island Summer Time"
    },
    "Pacific/Efate": {
        "STZ"   : "Vanuatu Time",
        "DSTZ"  : ""
    },
    "Pacific/Enderbury": {
        "STZ"   : "Phoenix Island Time",
        "DSTZ"  : ""
    },
    "Pacific/Fakaofo": {
        "STZ"   : "Tokelau Time",
        "DSTZ"  : ""
    },
    "Pacific/Fiji": {
        "STZ"   : "Fiji Time",
        "DSTZ"  : ""
    },
    "Pacific/Funafuti": {
        "STZ"   : "Tuvalu Time",
        "DSTZ"  : ""
    },
    "Pacific/Galapagos": {
        "STZ"   : "Galápagos Time",
        "DSTZ"  : ""
    },
    "Pacific/Gambier": {
        "STZ"   : "Gambier Island Time",
        "DSTZ"  : ""
    },
    "Pacific/Guadalcanal": {
        "STZ"   : "Solomon Islands Time",
        "DSTZ"  : ""
    },
    "Pacific/Guam": {
        "STZ"   : "Chamorro Standard Time",
        "DSTZ"  : ""
    },
    "Pacific/Honolulu": {
        "STZ"   : "Hawaii–Aleutian Standard Time",
        "DSTZ"  : ""
    },
    "Pacific/Kiritimati": {
        "STZ"   : "Line Islands Time",
        "DSTZ"  : ""
    },
    "Pacific/Kosrae": {
        "STZ"   : "Kosrae Time",
        "DSTZ"  : ""
    },
    "Pacific/Kwajalein": {
        "STZ"   : "Marshall Islands Time",
        "DSTZ"  : ""
    },
    "Pacific/Majuro": {
        "STZ"   : "Marshall Islands Time",
        "DSTZ"  : ""
    },
    "Pacific/Marquesas": {
        "STZ"   : "Marquesas Islands Time",
        "DSTZ"  : ""
    },
    "Pacific/Midway": {
        "STZ"   : "Samoa Standard Time",
        "DSTZ"  : ""
    },    "Pacific/Nauru": {
        "STZ"   : "Nauru Time",
        "DSTZ"  : ""
    },
    "Pacific/Niue": {
        "STZ"   : "Niue Time",
        "DSTZ"  : ""
    },
    "Pacific/Norfolk": {
        "STZ"   : "Norfolk Island Time",
        "DSTZ"  : "Norfolk Island Daylight Time"
    },
    "Pacific/Noumea": {
        "STZ"   : "New Caledonia Time",
        "DSTZ"  : ""
    },
    "Pacific/Pago_Pago": {
        "STZ"   : "Samoa Standard Time",
        "DSTZ"  : ""
    },
    "Pacific/Palau": {
        "STZ"   : "Palau Time",
        "DSTZ"  : ""
    },
    "Pacific/Pitcairn": {
        "STZ"   : "Pacific Standard Time",
        "DSTZ"  : ""
    },
    "Pacific/Pohnpei": {
        "STZ"   : "Pohnpei Standard Time",
        "DSTZ"  : ""
    },
    "Pacific/Port_Moresby": {
        "STZ"   : "Papua New Guinea Time",
        "DSTZ"  : ""
    },
    "Pacific/Rarotonga": {
        "STZ"   : "Cook Islands Time",
        "DSTZ"  : ""
    },
    "Pacific/Saipan": {
        "STZ"   : "Chamorro Standard Time",
        "DSTZ"  : ""
    },
    "Pacific/Tahiti": {
        "STZ"   : "Tahiti Time",
        "DSTZ"  : ""
    },
    "Pacific/Tarawa": {
        "STZ"   : "Gilbert Island Time",
        "DSTZ"  : ""
    },
    "Pacific/Tongatapu": {
        "STZ"   : "Tonga Time",
        "DSTZ"  : ""
    },
    "Pacific/Wake": {
        "STZ"   : "Wake Island Time",
        "DSTZ"  : ""
    },
    "Pacific/Wallis": {
        "STZ"   : "Wallis and Futuna Time",
        "DSTZ"  : ""
    }
}
