{
    "Baker Island Time": {
        "ShortName": "BIT",
        "LongName": "(UTC-12:00) Baker Island Time",
        "Offset": -12,
        "DSTZ": "",
        "STZ": ""
    },
    "International Day Line West": {
        "ShortName": "IDLW",
        "LongName": "(UTC-12:00) International Day Line West",
        "Offset": -12,
        "DSTZ": "",
        "STZ": ""
    },
    "Niue Time": {
        "ShortName": "NUT",
        "LongName": "(UTC-11:00) Niue Time",
        "Offset": -11,
        "DSTZ": "Samoa Daylight Time",
        "STZ": ""
    },
    "Samoa Standard Time": {
        "ShortName": "SST",
        "LongName": "(UTC-11:00) Samoa Standard Time",
        "Offset": -11,
        "DSTZ": "Samoa Daylight Time",
        "STZ": ""
    },
    "Cook Islands Time": {
        "ShortName": "CKT",
        "LongName": "(UTC-10:00) Cook Islands Time",
        "Offset": -10,
        "DSTZ": "",
        "STZ": ""
    },
    "Hawaii–Aleutian Standard Time": {
        "ShortName": "HST",
        "LongName": "(UTC-10:00) Hawaii–Aleutian Standard Time",
        "Offset": -10,
        "DSTZ": "Hawaii–Aleutian Daylight Time",
        "STZ": ""
    },
    "Samoa Daylight Time": {
        "ShortName": "SDT",
        "LongName": "(UTC-10:00) Samoa Daylight Time",
        "Offset": -10,
        "DSTZ": "",
        "STZ": "Samoa Standard Time"
    },
    "Tahiti Time": {
        "ShortName": "TAHT",
        "LongName": "(UTC-10:00) Tahiti Time",
        "Offset": -10,
        "DSTZ": "",
        "STZ": ""
    },
    "Marquesas Islands Time": {
        "ShortName": "MIT",
        "LongName": "(UTC−09:30) Marquesas Islands Time",
        "Offset": -9.5,
        "DSTZ": "",
        "STZ": ""
    },
    "Alaska Standard Time": {
        "ShortName": "AKST",
        "LongName": "(UTC-09:00) Alaska Standard Time",
        "Offset": -9,
        "DSTZ": "Alaska Daylight Time",
        "STZ": ""
    },
    "Gambier Island Time": {
        "ShortName": "GIT",
        "LongName": "(UTC−09:00) Gambier Island Time",
        "Offset": -9,
        "DSTZ": "",
        "STZ": ""
    },
    "Hawaii–Aleutian Daylight Time": {
        "ShortName": "HDT",
        "LongName": "(UTC-9:00) Hawaii–Aleutian Daylight Time",
        "Offset": -9,
        "DSTZ": "",
        "STZ": "Hawaii–Aleutian Standard Time"
    },
    "Alaska Daylight Time": {
        "ShortName": "AKDT",
        "LongName": "(UTC-08:00) Alaska Standard Time",
        "Offset": -8,
        "DSTZ": "",
        "STZ": "Alaska Standard Time"
    },
    "Pacific Standard Time": {
        "ShortName": "PST",
        "LongName": "(UTC-08:00) Pacific Standard Time",
        "Offset": -8,
        "DSTZ": "Pacific Daylight Time",
        "STZ": ""
    },
    "Mountain Standard Time": {
        "ShortName": "MST",
        "LongName": "(UTC-07:00) Mountain Standard Time",
        "Offset": -7,
        "DSTZ": "Mountain Daylight Time",
        "STZ": ""
    },
    "Pacific Daylight Time": {
        "ShortName": "PDT",
        "LongName": "(UTC-07:00) Pacific Daylight Time",
        "Offset": -7,
        "DSTZ": "",
        "STZ": "Pacific Standard Time"
    },
    "Central Standard Time": {
        "ShortName": "CST",
        "LongName": "(UTC-06:00) Central Standard Time",
        "Offset": -6,
        "DSTZ": "Central Daylight Time",
        "STZ": ""
    },
    "Central Time": {
        "ShortName": "CT",
        "LongName": "(UTC-06:00) Central Time",
        "Offset": -6,
        "DSTZ": "",
        "STZ": ""
    },
    "Easter Island Standard Time": {
        "ShortName": "EAST",
        "LongName": "(UTC-06:00) Easter Island Standard Time",
        "Offset": -6,
        "DSTZ": "Easter Island Summer Time",
        "STZ": ""
    },
    "Galápagos Time": {
        "ShortName": "GIT",
        "LongName": "(UTC-06:00) Galápagos Time",
        "Offset": -6,
        "DSTZ": "",
        "STZ": ""
    },
    "Mountain Daylight Time": {
        "ShortName": "MDT",
        "LongName": "(UTC-07:00) Mountain Daylight Time",
        "Offset": -6,
        "DSTZ": "",
        "STZ": "Mountain Standard Time"
    },
    "Acre Time": {
        "ShortName": "ACT",
        "LongName": "(UTC-05:00) Acre Time",
        "Offset": -5,
        "DSTZ": "",
        "STZ": ""
    },
    "Central Daylight Time": {
        "ShortName": "CDT",
        "LongName": "(UTC-05:00) Central Daylight Time",
        "Offset": -5,
        "DSTZ": "",
        "STZ": "Central Standard Time"
    },
    "Colombia Time": {
        "ShortName": "COT",
        "LongName": "(UTC-05:00) Colombia Time",
        "Offset": -5,
        "DSTZ": "Colombia Summer Time",
        "STZ": ""
    },
    "Cuba Standard Time": {
        "ShortName": "ACT",
        "LongName": "(UTC-05:00) Cuba Standard Time",
        "Offset": -5,
        "DSTZ": "Cuba Daylight Time",
        "STZ": ""
    },
    "Easter Island Summer Time": {
        "ShortName": "EASST",
        "LongName": "(UTC-05:00) Easter Island Summer Time",
        "Offset": -5,
        "DSTZ": "",
        "STZ": "Easter Island Standard Time"
    },
    "Ecuador Time": {
        "ShortName": "ECT",
        "LongName": "(UTC-05:00) Central Time",
        "Offset": -5,
        "DSTZ": "",
        "STZ": ""
    },
    "Eastern Standard Time": {
        "ShortName": "EST",
        "LongName": "(UTC-05:00) Eastern Standard Time",
        "Offset": -5,
        "DSTZ": "Eastern Daylight Time",
        "STZ": ""
    },
    "Peru Time": {
        "ShortName": "PET",
        "LongName": "(UTC-05:00) Peru Time",
        "Offset": -5,
        "DSTZ": "",
        "STZ": ""
    },
    "Amazon Time": {
        "ShortName": "AMT",
        "LongName": "(UTC-04:00) Amazon Time",
        "Offset": -4,
        "DSTZ": "Amazon Summer Time",
        "STZ": ""
    },
    "Atlantic Standard Time": {
        "ShortName": "AST",
        "LongName": "(UTC-04:00) Atlantic Standard Time",
        "Offset": -4,
        "DSTZ": "Atlantic Daylight Time",
        "STZ": ""
    },
    "Bolivia Time": {
        "ShortName": "BOT",
        "LongName": "(UTC-04:00) Bolivia Time",
        "Offset": -4,
        "DSTZ": "",
        "STZ": ""
    },
    "Cuba Daylight Time": {
        "ShortName": "CDT",
        "LongName": "(UTC-04:00) Cuba Daylight Time",
        "Offset": -4,
        "DSTZ": "",
        "STZ": "Cuba Standard Time"
    },
    "Chile Standard Time": {
        "ShortName": "CLT",
        "LongName": "(UTC-04:00) Chile Standard Time",
        "Offset": -4,
        "DSTZ": "Chile Summer Time",
        "STZ": ""
    },
    "Colombia Summer Time": {
        "ShortName": "COT",
        "LongName": "(UTC-04:00) Colombia Summer Time",
        "Offset": -4,
        "DSTZ": "",
        "STZ": "Colombia Time"
    },
    "Eastern Caribbean Time": {
        "ShortName": "ECT",
        "LongName": "(UTC-04:00) Eastern Caribbean Time",
        "Offset": -4,
        "DSTZ": "",
        "STZ": ""
    },
    "Eastern Daylight Time": {
        "ShortName": "EDT",
        "LongName": "(UTC-04:00) Eastern Daylight Time",
        "Offset": -4,
        "DSTZ": "",
        "STZ": "Eastern Standard Time"
    },
    "Falkland Islands Time": {
        "ShortName": "FKT",
        "LongName": "(UTC-04:00) Falkland Islands Time",
        "Offset": -4,
        "DSTZ": "Falkland Islands Summer Time",
        "STZ": ""
    },
    "Guyana Time": {
        "ShortName": "GYT",
        "LongName": "(UTC-04:00) Guyana Time",
        "Offset": -4,
        "DSTZ": "",
        "STZ": ""
    },
    "Paraguay Time": {
        "ShortName": "PYT",
        "LongName": "(UTC-04:00) Paraguay Time",
        "Offset": -4,
        "DSTZ": "Paraguay Summer Time",
        "STZ": ""
    },
    "Venezuelan Standard Time": {
        "ShortName": "VET",
        "LongName": "(UTC-04:00) Venezuelan Standard Time",
        "Offset": -4,
        "DSTZ": "",
        "STZ": ""
    },
    "Newfoundland Standard Time": {
        "ShortName": "NST",
        "LongName": "(UTC-03:30) Newfoundland Standard Time",
        "Offset": -3.5,
        "DSTZ": "Newfoundland Daylight Time",
        "STZ": ""
    },
    "Atlantic Daylight Time": {
        "ShortName": "ADT",
        "LongName": "(UTC-03:00) Atlantic Daylight Time",
        "Offset": -3,
        "DSTZ": "",
        "STZ": "Atlantic Standard Time"
    },
    "Amazon Summer Time": {
        "ShortName": "AMT",
        "LongName": "(UTC-03:00) Amazon Summer Time",
        "Offset": -3,
        "DSTZ": "",
        "STZ": "Amazon Time"
    },
    "Argentina Time": {
        "ShortName": "ART",
        "LongName": "(UTC-03:00) Argentina Time",
        "Offset": -3,
        "DSTZ": "",
        "STZ": ""
    },
    "Brasília Time": {
        "ShortName": "BRT",
        "LongName": "(UTC-03:00) Brasília Time",
        "Offset": -3,
        "DSTZ": "Brasília Summer Time",
        "STZ": ""
    },
    "Chile Summer Time": {
        "ShortName": "CLT",
        "LongName": "(UTC-03:00) Chile Summer Time",
        "Offset": -3,
        "DSTZ": "",
        "STZ": "Chile Standard Time"
    },
    "Falkland Islands Summer Time": {
        "ShortName": "FKST",
        "LongName": "(UTC-03:00) Falkland Islands Summer Time",
        "Offset": -3,
        "DSTZ": "",
        "STZ": "Falkland Islands Time"
    },
    "French Guiana Time": {
        "ShortName": "GFT",
        "LongName": "(UTC-03:00) French Guiana Time",
        "Offset": -3,
        "DSTZ": "",
        "STZ": ""
    },
    "Saint Pierre and Miquelon Standard Time": {
        "ShortName": "PMST",
        "LongName": "(UTC-03:00) Saint Pierre and Miquelon Standard Time",
        "Offset": -3,
        "DSTZ": "Saint Pierre and Miquelon Daylight Time",
        "STZ": ""
    },
    "Paraguay Summer Time": {
        "ShortName": "PYST",
        "LongName": "(UTC-03:00) Paraguay Summer Time",
        "Offset": -3,
        "DSTZ": "",
        "STZ": "Paraguay Time"
    },
    "Rothera Research Station Time": {
        "ShortName": "ROTT",
        "LongName": "(UTC-03:00) Rothera Research Station Time",
        "Offset": -3,
        "DSTZ": "",
        "STZ": ""
    },
    "Suriname Time": {
        "ShortName": "SRT",
        "LongName": "(UTC-03:00) Suriname Time",
        "Offset": -3,
        "DSTZ": "",
        "STZ": ""
    },
    "Uruguay Time": {
        "ShortName": "UYT",
        "LongName": "(UTC-03:00) Uruguay Time",
        "Offset": -3,
        "DSTZ": "",
        "STZ": ""
    },
    "West Greenland Time": {
        "ShortName": "WGT",
        "LongName": "(UTC-03:00) West Greenland Time",
        "Offset": -3,
        "DSTZ": "West Greenland Summer Time",
        "STZ": ""
    },
    "Newfoundland Daylight Time": {
        "ShortName": "NDT",
        "LongName": "(UTC-02:30) Newfoundland Daylight Time",
        "Offset": -2.5,
        "DSTZ": "Newfoundland Standard Time",
        "STZ": ""
    },
    "Brasília Summer Time": {
        "ShortName": "BRST",
        "LongName": "(UTC-02:00) Brasília Summer Time",
        "Offset": -2,
        "DSTZ": "",
        "STZ": "Brasília Time"
    },
    "Fernando de Noronha Time": {
        "ShortName": "FNT",
        "LongName": "(UTC-02:00) Fernando de Noronha Time",
        "Offset": -2,
        "DSTZ": "",
        "STZ": ""
    },
    "South Georgia and the South Sandwich Islands Time": {
        "ShortName": "GST",
        "LongName": "(UTC-02:00) South Georgia and the South Sandwich Islands Time",
        "Offset": -2,
        "DSTZ": "",
        "STZ": ""
    },
    "Saint Pierre and Miquelon Daylight Time": {
        "ShortName": "PMDT",
        "LongName": "(UTC-02:00) Saint Pierre and Miquelon Daylight Time",
        "Offset": -2,
        "DSTZ": "",
        "STZ": "Saint Pierre and Miquelon Standard Time"
    },
    "West Greenland Summer Time": {
        "ShortName": "WGsT",
        "LongName": "(UTC-02:00) West Greenland Summer Time",
        "Offset": -2,
        "DSTZ": "",
        "STZ": "West Greenland Time"
    },
    "Azores Standard Time": {
        "ShortName": "AZOT",
        "LongName": "(UTC-01:00) Azores Standard Time",
        "Offset": -1,
        "DSTZ": "Azores Summer Time",
        "STZ": ""
    },
    "Cape Verde Time": {
        "ShortName": "CVT",
        "LongName": "(UTC-01:00) Cape Verde Time",
        "Offset": -1,
        "DSTZ": "",
        "STZ": ""
    },
    "Eastern Greenland Time": {
        "ShortName": "EGT",
        "LongName": "(UTC-01:00) Eastern Greenland Time",
        "Offset": -1,
        "DSTZ": "Eastern Greenland Summer Time",
        "STZ": ""
    },
    "Azores Summer Time": {
        "ShortName": "AZOST",
        "LongName": "(UTC±00:00) Azores Summer Time",
        "Offset": 0,
        "DSTZ": "",
        "STZ": "Azores Standard Time"
    },
    "Eastern Greenland Summer Time": {
        "ShortName": "EGST",
        "LongName": "(UTC±00:00) Eastern Greenland Summer Time",
        "Offset": 0,
        "DSTZ": "",
        "STZ": "Eastern Greenland Time"
    },
    "Greenwich Mean Time": {
        "ShortName": "GMT",
        "LongName": "(UTC±00:00) Greenwich Mean Time",
        "Offset": 0,
        "DSTZ": "",
        "STZ": ""
    },
    "Coordinated Universal Time": {
        "ShortName": "UTC",
        "LongName": "(UTC±00:00) Coordinated Universal Time",
        "Offset": 0,
        "DSTZ": "",
        "STZ": ""
    },
    "Western European Time": {
        "ShortName": "WET",
        "LongName": "(UTC±00:00) Western European Time",
        "Offset": 0,
        "DSTZ": "Western European Summer Time",
        "STZ": ""
    },
    "British Summer Time": {
        "ShortName": "BST",
        "LongName": "(UTC+01:00) British Summer Time",
        "Offset": 1,
        "DSTZ": "",
        "STZ": ""
    },
    "Central European Time": {
        "ShortName": "CET",
        "LongName": "(UTC+01:00) Central European Time",
        "Offset": 1,
        "DSTZ": "Central European Summer Time",
        "STZ": ""
    },
    "Irish Standard Time": {
        "ShortName": "IST",
        "LongName": "(UTC+01:00) Irish Standard Time",
        "Offset": 1,
        "DSTZ": "",
        "STZ": ""
    },
    "West Africa Time": {
        "ShortName": "WAT",
        "LongName": "(UTC+01:00) West Africa Time",
        "Offset": 1,
        "DSTZ": "West Africa Summer Time",
        "STZ": ""
    },
    "Western European Summer Time": {
        "ShortName": "WEST",
        "LongName": "(UTC+01:00) Western European Summer Time",
        "Offset": 1,
        "DSTZ": "",
        "STZ": "Western European Time"
    },
    "Central Africa Time": {
        "ShortName": "CAT",
        "LongName": "(UTC+02:00) Central Africa Time",
        "Offset": 2,
        "DSTZ": "",
        "STZ": ""
    },
    "Central European Summer Time": {
        "ShortName": "CEST",
        "LongName": "(UTC+02:00) Central European Summer Time",
        "Offset": 2,
        "DSTZ": "",
        "STZ": "Central European Time"
    },
    "Eastern European Time": {
        "ShortName": "EET",
        "LongName": "(UTC+02:00) Eastern European Time",
        "Offset": 2,
        "DSTZ": "Eastern European Summer Time",
        "STZ": ""
    },
    "Israel Standard Time": {
        "ShortName": "IST",
        "LongName": "(UTC+02:00) Israel Standard Time",
        "Offset": 2,
        "DSTZ": "Israel Daylight Time",
        "STZ": ""
    },
    "Kaliningrad Time": {
        "ShortName": "KALT",
        "LongName": "(UTC+02:00) Kaliningrad Time",
        "Offset": 2,
        "DSTZ": "",
        "STZ": ""
    },
    "South African Standard Time": {
        "ShortName": "SAST",
        "LongName": "(UTC+02:00) South African Standard Time",
        "Offset": 2,
        "DSTZ": "",
        "STZ": ""
    },
    "West Africa Summer Time": {
        "ShortName": "WAST",
        "LongName": "(UTC+02:00) West Africa Summer Time",
        "Offset": 2,
        "DSTZ": "",
        "STZ": "West Africa Time"
    },
    "Arabia Standard Time": {
        "ShortName": "AST",
        "LongName": "(UTC+03:00) Arabia Standard Time",
        "Offset": 3,
        "DSTZ": "",
        "STZ": ""
    },
    "Eastern Africa Time": {
        "ShortName": "EAT",
        "LongName": "(UTC+03:00) East Africa Time",
        "Offset": 3,
        "DSTZ": "",
        "STZ": ""
    },
    "Eastern European Summer Time": {
        "ShortName": "EEST",
        "LongName": "(UTC+03:00) Eastern European Summer Time",
        "Offset": 3,
        "DSTZ": "",
        "STZ": "Eastern European Time"
    },
    "Further-eastern European Time": {
        "ShortName": "FET",
        "LongName": "(UTC+03:00) Further-eastern European Time",
        "Offset": 3,
        "DSTZ": "",
        "STZ": ""
    },
    "Israel Daylight Time": {
        "ShortName": "IDT",
        "LongName": "(UTC+03:00) Israel Daylight Time",
        "Offset": 3,
        "DSTZ": "Israel Standard Time",
        "STZ": ""
    },
    "Indian Ocean Time": {
        "ShortName": "IOT",
        "LongName": "(UTC+03:00) Indian Ocean Time",
        "Offset": 3,
        "DSTZ": "",
        "STZ": ""
    },
    "Moscow Time": {
        "ShortName": "MSK",
        "LongName": "(UTC+03:00) Moscow Time",
        "Offset": 3,
        "DSTZ": "",
        "STZ": ""
    },
    "Showa Station Time": {
        "ShortName": "SYOT",
        "LongName": "(UTC+03:00) Showa Station Time",
        "Offset": 3,
        "DSTZ": "",
        "STZ": ""
    },
    "Turkey Time": {
        "ShortName": "TRT",
        "LongName": "(UTC+03:00) Turkey Time",
        "Offset": 3,
        "DSTZ": "",
        "STZ": ""
    },
    "Iran Standard Time": {
        "ShortName": "IRST",
        "LongName": "(UTC+03:30) Iran Standard Time",
        "Offset": 3.5,
        "DSTZ": "Iran Daylight Time",
        "STZ": ""
    },
    "Armenia Time": {
        "ShortName": "AMT",
        "LongName": "(UTC+04:00) Armenia Time",
        "Offset": 4,
        "DSTZ": "",
        "STZ": ""
    },
    "Azerbaijan Time": {
        "ShortName": "AZT",
        "LongName": "(UTC+04:00) Azerbaijan Time",
        "Offset": 4,
        "DSTZ": "",
        "STZ": ""
    },
    "Georgia Standard Time": {
        "ShortName": "GET",
        "LongName": "(UTC+04:00) Georgia Standard Time",
        "Offset": 4,
        "DSTZ": "",
        "STZ": ""
    },
    "Gulf Standard Time": {
        "ShortName": "GST",
        "LongName": "(UTC+04:00) Gulf Standard Time",
        "Offset": 4,
        "DSTZ": "",
        "STZ": ""
    },
    "Mauritius Time": {
        "ShortName": "MUT",
        "LongName": "(UTC+04:00) Mauritius Time",
        "Offset": 4,
        "DSTZ": "",
        "STZ": ""
    },
    "MSK+1": {
        "ShortName": "MSK+1",
        "LongName": "(UTC+04:00) MSK+1",
        "Offset": 4,
        "DSTZ": "",
        "STZ": ""
    },
    "Réunion Time": {
        "ShortName": "RET",
        "LongName": "(UTC+04:00) Réunion Time",
        "Offset": 4,
        "DSTZ": "",
        "STZ": ""
    },
    "Samara Time": {
        "ShortName": "SAMT",
        "LongName": "(UTC+04:00) Samara Time",
        "Offset": 4,
        "DSTZ": "",
        "STZ": ""
    },
    "Seychelles Time": {
        "ShortName": "SCT",
        "LongName": "(UTC+04:00) Seychelles Time",
        "Offset": 4,
        "DSTZ": "",
        "STZ": ""
    },
    "Volgograd Time": {
        "ShortName": "VOLT",
        "LongName": "(UTC+04:00) Volgograd Time",
        "Offset": 4,
        "DSTZ": "",
        "STZ": ""
    },
    "Afghanistan Time": {
        "ShortName": "AFT",
        "LongName": "(UTC+04:30) Afghanistan Time",
        "Offset": 4.5,
        "DSTZ": "",
        "STZ": ""
    },
    "Iran Daylight Time": {
        "ShortName": "IRDT",
        "LongName": "(UTC+04:30) Iran Daylight Time",
        "Offset": 4.5,
        "DSTZ": "",
        "STZ": "Iran Standard Time"
    },
    "Aqtobe Time": {
        "ShortName": "AQTT",
        "LongName": "(UTC+05:00) Aqtobe Time",
        "Offset": 5,
        "DSTZ": "",
        "STZ": ""
    },
    "Heard and McDonald Islands Time": {
        "ShortName": "HMT",
        "LongName": "(UTC+05:00) Heard and McDonald Islands Time",
        "Offset": 5,
        "DSTZ": "",
        "STZ": ""
    },
    "Mawson Station Time": {
        "ShortName": "MAWT",
        "LongName": "(UTC+05:00) Mawson Station Time",
        "Offset": 5,
        "DSTZ": "",
        "STZ": ""
    },
    "Maldives Time": {
        "ShortName": "MVT",
        "LongName": "(UTC+05:00) Maldives Time",
        "Offset": 5,
        "DSTZ": "",
        "STZ": ""
    },
    "MSK+2": {
        "ShortName": "MSK+2",
        "LongName": "(UTC+05:00) MSK+2",
        "Offset": 5,
        "DSTZ": "",
        "STZ": ""
    },
    "Oral Time": {
        "ShortName": "ORAT",
        "LongName": "(UTC+05:00) Oral Time",
        "Offset": 5,
        "DSTZ": "",
        "STZ": ""
    },
    "Pakistan Standard Time": {
        "ShortName": "PKT",
        "LongName": "(UTC+05:00) Pakistan Standard Time",
        "Offset": 5,
        "DSTZ": "",
        "STZ": ""
    },
    "French Southern and Antarctic Time": {
        "ShortName": "TFT",
        "LongName": "(UTC+05:00) French Southern and Antarctic Time",
        "Offset": 5,
        "DSTZ": "",
        "STZ": ""
    },
    "Tajikistan Time": {
        "ShortName": "TJT",
        "LongName": "(UTC+05:00) Tajikistan Time",
        "Offset": 5,
        "DSTZ": "",
        "STZ": ""
    },
    "Turkmenistan Time": {
        "ShortName": "TMT",
        "LongName": "(UTC+05:00) Turkmenistan Time",
        "Offset": 5,
        "DSTZ": "",
        "STZ": ""
    },
    "Uzbekistan Time": {
        "ShortName": "UZT",
        "LongName": "(UTC+05:00) Uzbekistan Time",
        "Offset": 5,
        "DSTZ": "",
        "STZ": ""
    },
    "Yekaterinburg Time": {
        "ShortName": "YEKT",
        "LongName": "(UTC+05:00) Yekaterinburg Time",
        "Offset": 5,
        "DSTZ": "",
        "STZ": ""
    },
    "India Standard Time": {
        "ShortName": "IST",
        "LongName": "(UTC+05:30) India Standard Time",
        "Offset": 5.5,
        "DSTZ": "",
        "STZ": ""
    },
    "Sri Lanka Standard Time": {
        "ShortName": "SLST",
        "LongName": "(UTC+05:30) Sri Lanka Standard Time",
        "Offset": 5.5,
        "DSTZ": "",
        "STZ": ""
    },
    "Nepal Time": {
        "ShortName": "NPT",
        "LongName": "(UTC+05:45) Nepal Time",
        "Offset": 5.75,
        "DSTZ": "",
        "STZ": ""
    },
    "Alma-Ata Time": {
        "ShortName": "ALMT",
        "LongName": "(UTC+06:00) Alma-Ata Time",
        "Offset": 6,
        "DSTZ": "",
        "STZ": ""
    },
    "British Indian Ocean Time": {
        "ShortName": "BIOT",
        "LongName": "(UTC+06:00) British Indian Ocean Time",
        "Offset": 6,
        "DSTZ": "",
        "STZ": ""
    },
    "Bangladesh Standard Time": {
        "ShortName": "BST",
        "LongName": "(UTC+06:00) Bangladesh Standard Time",
        "Offset": 6,
        "DSTZ": "",
        "STZ": ""
    },
    "Bhutan Time": {
        "ShortName": "BTT",
        "LongName": "(UTC+06:00) Bhutan Time",
        "Offset": 6,
        "DSTZ": "",
        "STZ": ""
    },
    "Kyrgyzstan Time": {
        "ShortName": "KGT",
        "LongName": "(UTC+06:00) Kyrgyzstan Time",
        "Offset": 6,
        "DSTZ": "",
        "STZ": ""
    },
    "Indian Chagos Time": {
        "ShortName": "IOT",
        "LongName": "(UTC+06:00) Indian Chagos Time",
        "Offset": 6,
        "DSTZ": "",
        "STZ": ""
    },
    "Omsk Time": {
        "ShortName": "OMST",
        "LongName": "(UTC+06:00) Omsk Time",
        "Offset": 6,
        "DSTZ": "",
        "STZ": ""
    },
    "Vostok Station Time": {
        "ShortName": "VOST",
        "LongName": "(UTC+06:00) Vostok Station Time",
        "Offset": 6,
        "DSTZ": "",
        "STZ": ""
    },
    "Cocos Islands Time": {
        "ShortName": "CCT",
        "LongName": "(UTC+06:30) Cocos Islands Time",
        "Offset": 6.5,
        "DSTZ": "",
        "STZ": ""
    },
    "Myanmar Standard Time": {
        "ShortName": "MMT",
        "LongName": "(UTC+06:30) Myanmar Standard Time",
        "Offset": 6.5,
        "DSTZ": "",
        "STZ": ""
    },
    "Christmas Island Time": {
        "ShortName": "CXT",
        "LongName": "(UTC+07:00) Christmas Island Time",
        "Offset": 7,
        "DSTZ": "",
        "STZ": ""
    },
    "Davis Time": {
        "ShortName": "DAVT",
        "LongName": "(UTC+07:00) Davis Time",
        "Offset": 7,
        "DSTZ": "",
        "STZ": ""
    },
    "Hovd Time": {
        "ShortName": "HOVT",
        "LongName": "(UTC+07:00) Hovd Time",
        "Offset": 7,
        "DSTZ": "",
        "STZ": ""
    },
    "Indochina Time": {
        "ShortName": "ICT",
        "LongName": "(UTC+07:00) Indochina Time",
        "Offset": 7,
        "DSTZ": "",
        "STZ": ""
    },
    "Krasnoyarsk Time": {
        "ShortName": "KRAT",
        "LongName": "(UTC+07:00) Krasnoyarsk Time",
        "Offset": 7,
        "DSTZ": "",
        "STZ": ""
    },
    "Novosibirsk Time": {
        "ShortName": "NOVT",
        "LongName": "(UTC+07:00) Novosibirsk Time",
        "Offset": 7,
        "DSTZ": "",
        "STZ": ""
    },
    "MSK+4": {
        "ShortName": "MSK+4",
        "LongName": "(UTC+07:00) MSK+4",
        "Offset": 7,
        "DSTZ": "",
        "STZ": ""
    },
    "Thailand Standard Time": {
        "ShortName": "THA",
        "LongName": "(UTC+07:00) Thailand Standard Time",
        "Offset": 7,
        "DSTZ": "",
        "STZ": ""
    },
    "Western Indonesian Time": {
        "ShortName": "WIB",
        "LongName": "(UTC+07:00) Western Indonesian Time",
        "Offset": 7,
        "DSTZ": "",
        "STZ": ""
    },
    "Australian Western Standard Time": {
        "ShortName": "WIB",
        "LongName": "(UTC+08:00) Australian Western Standard Time",
        "Offset": 8,
        "DSTZ": "",
        "STZ": ""
    },
    "Brunei Darussalam Time": {
        "ShortName": "BNT",
        "LongName": "(UTC+08:00) Brunei Darussalam Time",
        "Offset": 8,
        "DSTZ": "",
        "STZ": ""
    },
    "Casey Time": {
        "ShortName": "CAST",
        "LongName": "(UTC+08:00) Casey Time",
        "Offset": 8,
        "DSTZ": "Casey summer Time",
        "STZ": ""
    },
    "Choibalsan Standard Time": {
        "ShortName": "CHOT",
        "LongName": "(UTC+08:00) Choibalsan Standard Time",
        "Offset": 8,
        "DSTZ": "Choibalsan Summer Time",
        "STZ": ""
    },
    "Clipperton Island Standard Time": {
        "ShortName": "CIST",
        "LongName": "(UTC+08:00) Clipperton Island Standard Time",
        "Offset": 8,
        "DSTZ": "",
        "STZ": ""
    },
    "China Standard Time": {
        "ShortName": "CST",
        "LongName": "(UTC+08:00) China Standard Time",
        "Offset": 8,
        "DSTZ": "",
        "STZ": ""
    },
    "Hong Kong Time": {
        "ShortName": "HKT",
        "LongName": "(UTC+08:00) Hong Kong Time",
        "Offset": 8,
        "DSTZ": "",
        "STZ": ""
    },
    "Irkutsk Time": {
        "ShortName": "IRKT",
        "LongName": "(UTC+08:00) Irkutsk Time",
        "Offset": 8,
        "DSTZ": "",
        "STZ": ""
    },
    "Malaysia Time": {
        "ShortName": "MYT",
        "LongName": "(UTC+08:00) Malaysia Time",
        "Offset": 8,
        "DSTZ": "",
        "STZ": ""
    },
    "Philippine Time": {
        "ShortName": "PHT",
        "LongName": "(UTC+08:00) Philippine Time",
        "Offset": 8,
        "DSTZ": "",
        "STZ": ""
    },
    "Singapore Time": {
        "ShortName": "PHT",
        "LongName": "(UTC+08:00) Singapore Time",
        "Offset": 8,
        "DSTZ": "",
        "STZ": ""
    },
    "Ulaanbaatar Standard Time": {
        "ShortName": "ULAT",
        "LongName": "(UTC+08:00) Ulaanbaatar Standard Time",
        "Offset": 8,
        "DSTZ": "Ulaanbaatar Daylight Time",
        "STZ": ""
    },
    "Central Indonesia Time": {
        "ShortName": "WITA",
        "LongName": "(UTC+08:00) Central Indonesia Time",
        "Offset": 8,
        "DSTZ": "",
        "STZ": ""
    },
    "Western Standard Time": {
        "ShortName": "WST",
        "LongName": "(UTC+08:00) Western Standard Time",
        "Offset": 8,
        "DSTZ": "",
        "STZ": ""
    },
    "Choibalsan Summer Time": {
        "ShortName": "CHOST",
        "LongName": "(UTC+09:00) Choibalsan Summer Time",
        "Offset": 9,
        "DSTZ": "",
        "STZ": "Choibalsan Standard Time"
    },
    "Korea Standard Time": {
        "ShortName": "KST",
        "LongName": "(UTC+09:00) Korea Standard Time",
        "Offset": 9,
        "DSTZ": "",
        "STZ": ""
    },
    "Japan Standard Time": {
        "ShortName": "JST",
        "LongName": "(UTC+09:00) Japan Standard Time",
        "Offset": 9,
        "DSTZ": "",
        "STZ": ""
    },
    "Palau Time": {
        "ShortName": "PWT",
        "LongName": "(UTC+09:00) Palau Time",
        "Offset": 9,
        "DSTZ": "",
        "STZ": ""
    },
    "Timor Leste Time": {
        "ShortName": "TLT",
        "LongName": "(UTC+09:00) Timor Leste Time",
        "Offset": 9,
        "DSTZ": "",
        "STZ": ""
    },
    "Ulaanbaatar Summer Time": {
        "ShortName": "ULAST",
        "LongName": "(UTC+09:00) Ulaanbaatar Summer Time",
        "Offset": 9,
        "DSTZ": "",
        "STZ": "Ulaanbaatar Standard Time"
    },
    "Eastern Indonesian Time": {
        "ShortName": "WIT",
        "LongName": "(UTC+09:00) Eastern Indonesian Time",
        "Offset": 9,
        "DSTZ": "",
        "STZ": ""
    },
    "Yakutsk Time": {
        "ShortName": "YAKT",
        "LongName": "(UTC+09:00) Yakutsk Time",
        "Offset": 9,
        "DSTZ": "",
        "STZ": ""
    },
    "Australian Central Standard Time": {
        "ShortName": "ACST",
        "LongName": "(UTC+09:30) Australian Central Standard Time",
        "Offset": 9.5,
        "DSTZ": "Australian Central Daylight Time",
        "STZ": ""
    },
    "Australian Eastern Standard Time": {
        "ShortName": "AET",
        "LongName": "(UTC+10:00) Australian Eastern Standard Time",
        "Offset": 10,
        "DSTZ": "Australian Eastern Daylight Time",
        "STZ": ""
    },
    "Chamorro Standard Time": {
        "ShortName": "CHST",
        "LongName": "(UTC+10:00) Chamorro Standard Time",
        "Offset": 10,
        "DSTZ": "",
        "STZ": ""
    },
    "Chuuk Time": {
        "ShortName": "CHUT",
        "LongName": "(UTC+10:00) Chuuk Time",
        "Offset": 10,
        "DSTZ": "",
        "STZ": ""
    },
    "Dumont d'Urville Time": {
        "ShortName": "DDUT",
        "LongName": "(UTC+10:00) Dumont d'Urville Time",
        "Offset": 10,
        "DSTZ": "",
        "STZ": ""
    },
    "Papua New Guinea Time": {
        "ShortName": "PGT",
        "LongName": "(UTC+10:00) Papua New Guinea Time",
        "Offset": 10,
        "DSTZ": "",
        "STZ": ""
    },
    "Vladivostok Time": {
        "ShortName": "VLAT",
        "LongName": "(UTC+10:00) Vladivostok Time",
        "Offset": 10,
        "DSTZ": "",
        "STZ": ""
    },
    "Australian Central Daylight Time": {
        "ShortName": "ACDT",
        "LongName": "(UTC+10:30) Australian Central Daylight Time",
        "Offset": 10.5,
        "DSTZ": "",
        "STZ": "Australian Central Standard Time"
    },
    "Lord Howe Standard Time": {
        "ShortName": "LHST",
        "LongName": "(UTC+10:30) Lord Howe Standard Tim",
        "Offset": 10.5,
        "DSTZ": "Lord Howe Daylight Time",
        "STZ": ""
    },
    "Australian Eastern Daylight Time": {
        "ShortName": "AEDT",
        "LongName": "(UTC+11:00) Australian Eastern Daylight Time",
        "Offset": 11,
        "DSTZ": "",
        "STZ": "Australian Eastern Time"
    },
    "Bougainville Standard Time": {
        "ShortName": "BST",
        "LongName": "(UTC+11:00) Bougainville Standard Time",
        "Offset": 11,
        "DSTZ": "",
        "STZ": ""
    },
    "Casey Summer Time": {
        "ShortName": "CAST",
        "LongName": "(UTC+11:00) Casey Summer Time",
        "Offset": 11,
        "DSTZ": "",
        "STZ": "Casey Time"
    },
    "Kosrae Time": {
        "ShortName": "KOST",
        "LongName": "(UTC+11:00) Kosrae Time",
        "Offset": 11,
        "DSTZ": "",
        "STZ": ""
    },
    "Lord Howe Daylight Time": {
        "ShortName": "LHST",
        "LongName": "(UTC+11:00) Lord Howe Daylight Time",
        "Offset": 11,
        "DSTZ": "",
        "STZ": "Lord Howe Standard Time"
    },
    "Macquarie Island Station Time": {
        "ShortName": "MIST",
        "LongName": "(UTC+11:00) Macquarie Island Station Time",
        "Offset": 11,
        "DSTZ": "",
        "STZ": ""
    },
    "Magadan Time": {
        "ShortName": "NCT",
        "LongName": "(UTC+11:00) Magadan Time",
        "Offset": 11,
        "DSTZ": "",
        "STZ": ""
    },
    "New Caledonia Time": {
        "ShortName": "NCT",
        "LongName": "(UTC+11:00) New Caledonia Time",
        "Offset": 11,
        "DSTZ": "",
        "STZ": ""
    },
    "Norfolk Island Time": {
        "ShortName": "NFT",
        "LongName": "(UTC+11:00) Norfolk Island Time",
        "Offset": 11,
        "DSTZ": "Norfolk Island Daylight Time",
        "STZ": ""
    },
    "Pohnpei Standard Time": {
        "ShortName": "PONT",
        "LongName": "(UTC+11:00) Pohnpei Standard Time",
        "Offset": 11,
        "DSTZ": "",
        "STZ": ""
    },
    "Sakhalin Island Time": {
        "ShortName": "SAKT",
        "LongName": "(UTC+11:00) Sakhalin Island Time",
        "Offset": 11,
        "DSTZ": "",
        "STZ": ""
    },
    "Solomon Islands Time": {
        "ShortName": "SBT",
        "LongName": "(UTC+11:00) Solomon Islands Time",
        "Offset": 11,
        "DSTZ": "",
        "STZ": ""
    },
    "Srednekolymsk Time": {
        "ShortName": "SRET",
        "LongName": "(UTC+11:00) Srednekolymsk Time",
        "Offset": 11,
        "DSTZ": "",
        "STZ": ""
    },
    "Vanuatu Time": {
        "ShortName": "VUT",
        "LongName": "(UTC+11:00) Vanuatu Time",
        "Offset": 11,
        "DSTZ": "",
        "STZ": ""
    },
    "Anadyr Time": {
        "ShortName": "ANAT",
        "LongName": "(UTC+12:00) Anadyr Time",
        "Offset": 12,
        "DSTZ": "",
        "STZ": ""
    },
    "Fiji Time": {
        "ShortName": "FJT",
        "LongName": "(UTC+12:00) Fiji Time",
        "Offset": 12,
        "DSTZ": "",
        "STZ": ""
    },
    "Gilbert Island Time": {
        "ShortName": "GILT",
        "LongName": "(UTC+12:00) Gilbert Island Time",
        "Offset": 12,
        "DSTZ": "",
        "STZ": ""
    },
    "Marshall Islands Time": {
        "ShortName": "MHT",
        "LongName": "(UTC+12:00) Marshall Islands Time",
        "Offset": 12,
        "DSTZ": "",
        "STZ": ""
    },
    "Norfolk Island Daylight Time": {
        "ShortName": "NFDT",
        "LongName": "(UTC+12:00) Norfolk Island Daylight Time",
        "Offset": 12,
        "DSTZ": "",
        "STZ": "Norfolk Island Time"
    },
    "Nauru Time": {
        "ShortName": "NRT",
        "LongName": "(UTC+12:00) Nauru Time",
        "Offset": 12,
        "DSTZ": "",
        "STZ": ""
    },
    "New Zealand Standard Time": {
        "ShortName": "NZST",
        "LongName": "(UTC+12:00) New Zealand Standard Time",
        "Offset": 12,
        "DSTZ": "New Zealand Daylight Time",
        "STZ": ""
    },
    "Kamchatka Time": {
        "ShortName": "PETT",
        "LongName": "(UTC+12:00) Kamchatka Time",
        "Offset": 12,
        "DSTZ": "",
        "STZ": ""
    },
    "Tuvalu Time": {
        "ShortName": "TVT",
        "LongName": "(UTC+12:00) Tuvalu Time",
        "Offset": 12,
        "DSTZ": "",
        "STZ": ""
    },
    "Wake Island Time": {
        "ShortName": "WAKT",
        "LongName": "(UTC+12:00) Wake Island Time",
        "Offset": 12,
        "DSTZ": "",
        "STZ": ""
    },
    "Wallis and Futuna Time": {
        "ShortName": "WFT",
        "LongName": "(UTC+12:00) Wallis and Futuna Time",
        "Offset": 12,
        "DSTZ": "",
        "STZ": ""
    },
    "Chatham Island Standard Time": {
        "ShortName": "CHAST",
        "LongName": "(UTC+12:45) Chatham Island Standard Time",
        "Offset": 12.75,
        "DSTZ": "Chatham Island Daylight Time",
        "STZ": ""
    },
    "New Zealand Daylight Time": {
        "ShortName": "NZDT",
        "LongName": "(UTC+13:00) New Zealand Daylight Time",
        "Offset": 13,
        "DSTZ": "",
        "STZ": "New Zealand Standard Time"
    },
    "Phoenix Island Time": {
        "ShortName": "PHOT",
        "LongName": "(UTC+13:00) Phoenix Island Time",
        "Offset": 13,
        "DSTZ": "",
        "STZ": ""
    },
    "Tokelau Time": {
        "ShortName": "TKT",
        "LongName": "(UTC+13:00) Tokelau Time",
        "Offset": 13,
        "DSTZ": "",
        "STZ": ""
    },
    "Tonga Time": {
        "ShortName": "TOT",
        "LongName": "(UTC+13:00) Tonga Time",
        "Offset": 13,
        "DSTZ": "",
        "STZ": ""
    },
    "West Samoa Summer Time": {
        "ShortName": "WSST",
        "LongName": "(UTC+13:00) West Samoa Sumer Time",
        "Offset": 13,
        "DSTZ": "",
        "STZ": "West Samoa Time"
    },
    "Chatham Island Daylight Time": {
        "ShortName": "CHADT",
        "LongName": "(UTC+13:45) Chatham Island Daylight Time",
        "Offset": 13.45,
        "DSTZ": "",
        "STZ": "Chatham Island Standard Time"
    },
    "Line Islands Time": {
        "ShortName": "TOT",
        "LongName": "(UTC+14:00) Line Islands Time",
        "Offset": 14,
        "DSTZ": "",
        "STZ": ""
    },
    "West Samoa Time": {
        "ShortName": "WST",
        "LongName": "(UTC+14:00) West Samoa Time",
        "Offset": 14,
        "DSTZ": "West Samoa Sumer Time",
        "STZ": ""
    }
}
