<?php
/**
 * @brief CaMykS database configuration file.
 * @details Engine / Configuration File
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Sep 2019
 * @date Modification: Nov 2019
 * @copyright 2019 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$configuration = array(
    'Database_Driver' => '',
    'Database_Host' => '',
    'Database_Port' => 0,
    'Database_Login' => '',
    'Database_Password' => '',
    'Database_Name' => '',
    'Database_Secure' => 0,
    'Database_TablePrefix' => '',
);
?>
