<?php
/**
 * @brief CaMykS admin configuration file.
 * @details Engine / Configuration File
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Sep 2019
 * @date Modification: Nov 2019
 * @copyright 2019 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$configuration = array(
    'Admin_Languages' => array(),
    'Admin_DefaultLanguage' => '',
    'Admin_Theme' => '',
    'Admin_EntryPoint' => 'admin.php',
    'Admin_SSL' => 0,
    'Admin_KeepAlive' => 0,
    'Admin_SaveMode' => 0, // 0 : save and read | 1 : save and keep editing | 2 : save and leave
);
?>
