<?php
/**
 * @brief CaMykS admin configuration file.
 * @details Engine / Configuration File
 * @file Core/Configuration/admin.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: Sep 2019
 * @date Modification: Sep 2019
 * @copyright 2019 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$configuration = array(
    'admin_languages' => array(),
    'admin_defaultLanguage' => '',
    'admin_theme' => '',
    'admin_entryPoint' => 'admin.php',
    'admin_SSL' => 0,
    'admin_keepAlive' => 0,
);
?>
