<?php
/**
 * @brief CaMykS static description file.
 * @details Engine / Description File
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.3
 * @date Creation: Oct 2019
 * @date Modification: Nov 2019
 * @copyright 2019 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/**
 * @var string $this->name
 * @brief CaMykS name.
 */
$this->name = 'CaMykS';

/**
 * @var string $this->version
 * @brief CaMykS full version
 */
$this->version = '2.0p0';

/**
 * @var string $this->versionMajor
 * @brief CaMykS major version
 */
$this->versionMajor = '2.0';

/**
 * @var string $this->versionMinor
 * @brief CaMykS minor version
 */
$this->versionMinor = 'p0';

/**
 * @var string $this->lastModificationDate
 * @brief CaMykS last modification date
 */
$this->lastModificationDate = 'Thu, 3 Oct 2019 18:00:00 +0200';

/**
 * @var string $this->PHPMinVersion
 * @brief PHP minimal version to run CaMykS
 */
$this->PHPMinVersion = '5.3.26';

/**
 * @var string $this->libraryExtension
 * @brief CaMykS libraries extension
 */
$this->libraryExtension = '.php.inc';

/**
 * @var string $this->layoutExtension
 * @brief CaMykS layouts extension
 */
$this->layoutExtension = '.html.inc';

/**
 * @var string $this->websiteURL
 * @brief CaMykS Website
 */
$this->websiteURL = 'https://www.camyks.net';

/**
 * @var string $this->defaultLanguage
 * @brief CaMykS default language
 */
$this->defaultLanguage = 'en_GB';

?>
