<?php
/**
 * @brief CaMykS static description file.
 * @details Engine / Description File
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0pre6
 * @date Creation: Oct 2019
 * @date Modification: Feb 2021
 * @copyright 2019 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/**
 * @def CAMYKS_NAME
 * @brief CaMykS name.
 */
define('CAMYKS_NAME',                   'CaMykS');

/**
 * @def CAMYKS_VERSION
 * @brief CaMykS full version
 */
define('CAMYKS_VERSION',                '2.0pre0');

/**
 * @def CAMYKS_VERSIONMAJOR
 * @brief CaMykS major version
 */
define('CAMYKS_VERSIONMAJOR',           '2.0');

/**
 * @def CAMYKS_VERSIONMINOR
 * @brief CaMykS minor version
 */
define('CAMYKS_VERSIONMINOR',           'pre0');

/**
 * @def CAMYKS_LASTMODIFICATIONDATE
 * @brief CaMykS last modification date
 */
define('CAMYKS_LASTMODIFICATIONDATE',   'Thu, 3 Oct 2019 18:00:00 +0200');

/**
 * @def CAMYKS_PHPMINVERSION
 * @brief PHP minimal version to run CaMykS
 */
define('CAMYKS_PHPMINVERSION',          '5.3.26');

/**
 * @def CAMYKS_LIBRARYEXTENSION
 * @brief CaMykS libraries extension
 */
define('CAMYKS_LIBRARYEXTENSION',       '.php.inc');

/**
 * @def CAMYKS_LAYOUTEXTENSION
 * @brief CaMykS layouts extension
 */
define('CAMYKS_LAYOUTEXTENSION',        '.html.inc');

/**
 * @def CAMYKS_ASSETDATAEXTENSION
 * @brief CaMykS asset data extension
 */
define('CAMYKS_ASSETDATAEXTENSION',     '.json.inc');

/**
 * @def CAMYKS_DEFAULTLANGUAGE
 * @brief CaMykS default language
 */
define('CAMYKS_DEFAULTLANGUAGE',        'fr_FR');

/**
 * @def CAMYKS_WEBSITEURL
 * @brief CaMykS Website
 */
define('CAMYKS_WEBSITEURL',             'https://www.camyks.net');

?>
