<?php
/**
 * @brief CaMykS database configuration file.
 * @details Engine / Configuration File
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: Sep 2019
 * @date Modification: Sep 2019
 * @copyright 2019 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$configuration = array(
    'database_driver' => '',
    'database_host' => '',
    'database_port' => 0,
    'database_login' => '',
    'database_password' => '',
    'database_name' => '',
    'database_secure' => 0,
    'database_tablePrefix' => '',
);
?>
