{
    "DefaultComponents": [
    ],
    "DefaultModules": [
        "SystemPluginManager",
        "SystemAdministratorManager",
        "SystemConfigurationManager",
        "SystemFileStorageManager",
        "SystemLogManager",
        "SystemPrivacyPolicyManager",
        "SystemSessionManager",
        "SystemSitePageManager",
        "SystemUniqueIdManager"
    ],
    "DefaultTemplates": [
        "AdminPage"
    ],
    "DefaultThemes": [
    ]
}
