<?php
/**
 * @brief CaMykS engine configuration file.
 * @details Engine / Configuration File
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.2
 * @date Creation: Oct 2019
 * @date Modification: Nov 2019
 * @copyright 2019 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$configuration = array(
    'Engine_TimeZone' => 'Europe/Paris',
    'Engine_UserAgent' => 'Mozilla/5.0 (compatible; CaMykSRequest/1.0; +https://www.camyks.net/request_bot.html)',
    'Engine_ErrorLoggingLevel' => 'auto', // auto : value is defined from website status
    'Engine_ErrorLoggingOutput' => 'auto', // auto : value is defined from website status
    'Engine_PictureEditor' => 'gd',
);
?>
