<?php
/**
 * @brief CaMykS GDPR configuration file.
 * @details Engine / Configuration File
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: Nov 2019
 * @date Modification: Nov 2019
 * @copyright 2019 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$configuration = array(
    'GDPR_AnonymiseDataAfterValue' => 0,
    'GDPR_AnonymiseDataAfterUnit' => 'y',
    'GDPR_AnonymiseDataMethod' => 0, // 0 : blank data | 1 : shadowed data
    'GDPR_DeleteDataAfterValue' => 0,
    'GDPR_DeleteDataAfterUnit' => 'y',
);
?>
