<?php
/**
 * @brief CaMykS manager configuration file.
 * @details Engine / Configuration File
 * @file Core/Configuration/manager.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: Sep 2019
 * @date Modification: Sep 2019
 * @copyright 2019 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$configuration = array(
    'manager_password' => '',
    'manager_websitesPath' => '',
    'manager_restrainedIPs' => array(),
    'manager_SSL' => array(),
    'manager_displaySites' => 0,
    'manager_websitesSearchLevel' => 0,
);
?>
