<?php
/**
 * @brief CaMykS manager configuration file.
 * @details Engine / Configuration File
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.4
 * @date Creation: Sep 2019
 * @date Modification: Mar 2020
 * @copyright 2019 - 2020 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$configuration = array(
    'Manager_Password' => '',
    'Manager_WebsitesPath' => '../',
    'Manager_RestrainedIPs' => array(),
    'Manager_SSL' => 0,
    'Manager_DisplaySites' => 0,
    'Manager_WebsitesSearchLevel' => 0,
    'Manager_DefaultLanguage' => '',
    'Manager_Theme' => 'CaMykSStyle',
    'Manager_IndexRedirectURL' => '',
);
?>
