<?php
/**
 * @brief CaMykS plugins configuration file.
 * @details Engine / Configuration File
 * @file Core/Configuration/plugins.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: Sep 2019
 * @date Modification: Sep 2019
 * @copyright 2019 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$configuration = array(
    /* Admin Plugins */
    'plugins_adminLogin' => 'Tool_SystemAdminLogin',
    'plugins_adminPanel' => 'Tool_SystemAdminControlPanel',
    'plugins_adminList' => 'CaMykSAdminList',
    'plugins_adminEditor' => '',
    'plugins_adminFileManager' => '',

    /* Visit plugins */
    'plugins_visitCaptcha' => '',
);
?>
