<?php
/**
 * @brief CaMykS plugins configuration file.
 * @details Engine / Configuration File
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.2
 * @date Creation: Sep 2019
 * @date Modification: Nov 2019
 * @copyright 2019 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$configuration = array(
    /* Admin Plugins */
    'Plugins_AdminLogin'        => 'Tool_SystemAdminLogin',
    'Plugins_AdminPanel'        => 'Tool_SystemAdminControlPanel',
    'Plugins_AdminList'         => 'CaMykSAdminList',
    'Plugins_AdminEditor'       => '',
    'Plugins_AdminFileManager'  => '',
    'Plugins_AdminUIDManager'   => '',

    /* Visit plugins */
    'Plugins_VisitCaptcha' => '',
);
?>
