<?php
/**
 * @brief CaMykS visit configuration file.
 * @details Engine / Configuration File
 * @file Core/Configuration/visit.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: Sep 2019
 * @date Modification: Sep 2019
 * @copyright 2019 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$configuration = array(
    'visit_languages' => array(),
    'visit_defaultLanguage' => '',
    'visit_theme' => '',
    'visit_template' => '',
    'visit_SSL' => 0,
    'visit_mobileMode' => 0,
    'visit_autoLoadCaMykSJS' => 0,
    'visit_clientSideCache' => 1,
    'visit_serverSideCache' => 0,
);
?>
