<?php
/**
 * @brief CaMykS visit configuration file.
 * @details Engine / Configuration File
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Sep 2019
 * @date Modification: Nov 2019
 * @copyright 2019 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$configuration = array(
    'Visit_Languages' => array(),
    'Visit_DefaultLanguage' => '',
    'Visit_Theme' => '',
    'Visit_Template' => '',
    'Visit_SSL' => 0,
    'Visit_MobileMode' => 0,
    'Visit_AutoLoadCaMykSJS' => 0,
    'Visit_ClientSideCache' => 1,
    'Visit_ServerSideCache' => 0,
);
?>
