<?php
/**
 * @brief CaMykS companies data for client library.
 * @details Engine / Data Library
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0pre1
 * @date Creation: Feb 2020
 * @date Modification: Jan 2021
 * @copyright 2020 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * @warning This library is not loaded with CaMykS initialisation.
 */

$cClientCompanies = array(
    /* Alphabet */
    'alphabet' => array(
        'Name'      => 'Alphabet',
        'Link'      => 'https://abc.xyz/',
        'Country'   => 'us',
        'Status'    => 'Active',
        'Parent'    => null,
    ),

    /* Apple */
    'apple' => array(
        'Name'      => 'Apple',
        'Link'      => 'https://www.apple.com',
        'Country'   => 'us',
        'Status'    => 'Active',
        'Parent'    => null,
    ),

    /* The Chromium Project */
    'chromium' => array(
        'Name'      => 'The Chromium Project',
        'Link'      => 'https://www.chromium.org/Home',
        'Country'   => 'us',
        'Status'    => 'Active',
        'Parent'    => null,
    ),

    /* Ecosia */
    'ecosia' => array(
        'Name'      => 'Ecosia',
        'Link'      => 'https://ecosia.org',
        'Country'   => 'de',
        'Status'    => 'Active',
        'Parent'    => null,
    ),

    /* Google */
    'google' => array(
        'Name'      => 'Google',
        'Link'      => 'https://www.google.com',
        'Country'   => 'us',
        'Status'    => 'Active',
        'Parent'    => 'alphabet',
    ),

    /* Microsoft */
    'microsoft' => array(
        'Name'      => 'Microsoft',
        'Link'      => 'https://www.microsoft.com',
        'Country'   => 'us',
        'Status'    => 'Active',
        'Parent'    => null,
    ),

    /* Mozilla foundation */
    'mozilla' => array(
        'Name'      => 'Mozilla foundation',
        'Link'      => 'https://www.mozilla.org',
        'Country'   => 'us',
        'Status'    => 'Active',
        'Parent'    => null,
    ),

    /* Opera Software */
    'opera' => array(
        'Name'      => 'Opera Software',
        'Link'      => 'https://www.opera.com',
        'Country'   => 'no',
        'Status'    => 'Active',
        'Parent'    => null,
    ),
);
?>
