<?php
/**
 * @brief CaMykS manufacturers data for client library.
 * @details Engine / Data Library
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.0
 * @date Creation: Feb 2020
 * @date Modification: Feb 2020
 * @copyright 2020 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * @warning This library is not loaded with CaMykS initialisation.
 */

$cClientManufacturers = array(
    /* Apple */
    'apple' => array(
        'Name'      => 'Apple',
        'Link'      => 'https://www.apple.com',
        'Country'   => 'us',
        'Status'    => 'Active',
    ),

    /* Google */
    'google' => array(
        'Name'      => 'Google',
        'Link'      => 'https://www.google.com',
        'Country'   => 'us',
        'Status'    => 'Active',
    ),

    /* Microsoft */
    'microsoft' => array(
        'Name'      => 'Microsoft',
        'Link'      => 'https://www.microsoft.com',
        'Country'   => 'us',
        'Status'    => 'Active',
    ),
);
?>
