<?php
/**
 * @brief Cryptographer library french dictionary.
 * @details Engine / Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.0.1
 * @date Creation: Nov 2019
 * @date Modification: Feb 2021
 * @copyright 2019 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY,
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$locales = array(
    'Error_UnknownEngine' => 'Moteur d\'encryption inconnu.',
    'Error_EngineNotAvailable' => 'Moteur d\'encryption indisponible.',
    'Error_UnknownCipher' => 'M&eacute;thode de cipher inconnue.',
    'Error_KeyIsEmpty' => 'La cl&eacute; d\'encodage est vide.',
    'Error_IvIsEmpty' => 'Le vecteur d\'initialisation est vide.',
    'Error_ResultAltered' => 'Le r&eacute;sultat a &eacute;t&eacute; alter&eacute.',
    'Error_UnknownMCryptMode' => 'M&eacute;thode d\'encryption inconnue.',
);
?>
