<?php
/**
 * @brief PushNotification library french dictionnary.
 * @details Engine / Dictionnary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.0
 * @date Creation: Nov 2019
 * @date Modification: Nov 2019
 * @copyright 2019 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY,
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$locales = array(
    'Error_UnknownPlatform' => 'Plateforme inconnue.',
    'Error_UndefinedIdentifier' => 'Identifiant ind&eacute;termin&eacute;.',
    'Error_ServerConnectionFailed' => 'La connexion au serveur a &eacute;chou&eacute;e.',
    'Error_MessageRefused' => 'Message refus&eacute;.',
);
?>
