<?php
/**
 * @brief DatabaseConnector library french dictionary.
 * @details Engine / Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.0.1
 * @date Creation: Nov 2019
 * @date Modification: Feb 2021
 * @copyright 2019 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY,
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$locales = array(
    'Error_DriverUnknown' => 'Driver de base de donn&eacute;es inconnu.',
    'Error_DriverUnavailable' => 'Driver de base de donn&eacute;es indisponible.',
);
?>
