<?php
/**
 * @brief File library french dictionary.
 * @details Engine / Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.0.1
 * @date Creation: Nov 2019
 * @date Modification: Feb 2021
 * @copyright 2019 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY,
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$locales = array(
    /* Errors */
    'Error_FileDoesntExists'    => 'Le fichier n\'existe pas.',
    'Error_FileIsntAccessible'  => 'Le fichier n\'est pas accessible.',

    /* Short description */
    'ShortDesc_Image'       => 'Image',
    'ShortDesc_Audio'       => 'Audio',
    'ShortDesc_Video'       => 'Vid&eacute;o',
    'ShortDesc_Text'        => 'Texte',
    'ShortDesc_Font'        => 'Police d\'écriture',
    'ShortDesc_Script'      => 'Script',
    'ShortDesc_Archive'     => 'Archive',
    'ShortDesc_Document'    => 'Document',

    /* Long description */
    'LongDesc_Image'        => 'Fichier image',
    'LongDesc_Audio'        => 'Fichier audio',
    'LongDesc_Video'        => 'Fichier vid&eacute;o',
    'LongDesc_Text'         => 'Fichier texte',
    'LongDesc_Font'         => 'Police d\'écriture',
    'LongDesc_Script'       => 'Script',
    'LongDesc_Archive'      => 'Fichier archive',
    'LongDesc_Document'     => 'Document',
);
?>
