{
    "alphabet" : {
        "Name"      : "Alphabet",
        "Link"      : "https://abc.xyz/",
        "Country"   : "us",
        "Status"    : "Active",
        "Parent"    : null
    },

    "apple" : {
        "Name"      : "Apple",
        "Link"      : "https://www.apple.com",
        "Country"   : "us",
        "Status"    : "Active",
        "Parent"    : null
    },

    "chromium" : {
        "Name"      : "The Chromium Project",
        "Link"      : "https://www.chromium.org/Home",
        "Country"   : "us",
        "Status"    : "Active",
        "Parent"    : null
    },

    "ecosia" : {
        "Name"      : "Ecosia",
        "Link"      : "https://ecosia.org",
        "Country"   : "de",
        "Status"    : "Active",
        "Parent"    : null
    },

    "google" : {
        "Name"      : "Google",
        "Link"      : "https://www.google.com",
        "Country"   : "us",
        "Status"    : "Active",
        "Parent"    : "alphabet"
    },

    "microsoft" : {
        "Name"      : "Microsoft",
        "Link"      : "https://www.microsoft.com",
        "Country"   : "us",
        "Status"    : "Active",
        "Parent"    : null
    },

    "mozilla" : {
        "Name"      : "Mozilla foundation",
        "Link"      : "https://www.mozilla.org",
        "Country"   : "us",
        "Status"    : "Active",
        "Parent"    : null
    },

    "opera" : {
        "Name"      : "Opera Software",
        "Link"      : "https://www.opera.com",
        "Country"   : "no",
        "Status"    : "Active",
        "Parent"    : null
    }
}
