<?php
/**
 * @brief AdminPage template, french dictionary.
 * @details Plugin / Template Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.0.1
 * @date Creation: Mar 2020
 * @date Modification: Feb 2021
 * @copyright 2020 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY,
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$locales = array(
    'HeaderTitle' => 'Administration du site <br />%s',

    /* Action bar buttons */
    'Home' => 'Accueil',
    'Menu' => 'Menus &amp; r&eacute;glages',
    'LogOut' => 'D&eacute;connexion',
);
?>
