<?php
/**
 * @brief AdminPage template, french dictionary.
 * @details Plugin / Template Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0pre1
 * @date Creation: Mar 2020
 * @date Modification: Dec 2021
 * @copyright 2020 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY,
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$locales = array(
    'HeaderTitle' => 'Administration du site <br />%s',

    /* Action bar buttons */
    'Home' => 'Accueil',
    'Menu' => 'Menus &amp; r&eacute;glages',
    'LogOut' => 'D&eacute;connexion',

    /* Logout */
    'Logout_Message' => 'Vous allez &ecirc;tre d&eacute;connect&eacute;, &ecirc;tes vous s&ucirc;r ?',
    'Logout_AcceptButtonTitle' => 'Confirmer',
    'Logout_CloseButtonTitle' => 'Annuler',
);
?>
