<?php
/**
 * @brief CaMykS website configuration file.
 * @details Skeleton / Configuration File
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: Sep 2019
 * @date Modification: Sep 2019
 * @copyright 2019 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$configuration = array(
    'website_camyksPath' => '',
    'website_camyksMode' => '',
    'website_url' => '',
    'website_title' => '',
    'website_version' => '1.0',
    'website_status' => 0,
    'website_encoding' => 'UTF8',
    'website_CaMykSVersionInMeta' => 1,
    'website_author' => '',
);
?>
