<?php
/**
 * @brief CaMykS website configuration file.
 * @details Skeleton / Configuration File
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0pre7
 * @date Creation: Sep 2019
 * @date Modification: May 2021
 * @copyright 2019 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$configuration = array(
    'Website_Name' => '',
    'Website_CaMykSPath' => '',
    'Website_CaMykSMode' => '',
    'Website_URL' => '',
    'Website_Title' => '',
    'Website_Version' => '1.0',
    'Website_Status' => 0,  // 0: not installed | 1: live | 2: development | 3: full maintenance (no admin available) | 4: simple maintenance (admin available)
    'Website_Encoding' => 'UTF-8',
    'Website_Author' => '',
    'Website_DisplayCMSSignature' => true,
    'Website_LocalStorage' => 'files', // files | database
);
?>
