<?php
/**
 * @brief CaMykS website configuration file.
 * @details Skeleton / Configuration File
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.3
 * @date Creation: Sep 2019
 * @date Modification: Feb 2020
 * @copyright 2019 - 2020 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$configuration = array(
    'Website_CaMykSPath' => '',
    'Website_CaMykSMode' => '',
    'Website_URL' => '',
    'Website_URLMode' => '',
    'Website_Title' => '',
    'Website_Version' => '1.0',
    'Website_Status' => 0,  // 0: not installed | 1: live | 2: development | 3: full maintenance (no admin available) | 4: simple maintenance (admin available)
    'Website_Encoding' => 'UTF8',
    'Website_CaMykSVersionInMeta' => 1,
    'Website_Author' => '',
    'Website_HideCMSSignature' => false,
);
?>
