<?php
/**
 * @brief CaMykS main french dictionary.
 * @details Engine / Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0pre1
 * @date Creation: Feb 2021
 * @date Modification: Jun 2021
 * @copyright 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY,
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$locales = array(
    /* Yes / No */
    'Yes' => 'Oui',
    'No' => 'Non',

    /* Actions */
    'Save'  => 'Enregistrer',
    'Cancel' => 'Annuler',
    'Back' => 'Retour',
    'Continue' => 'Continuer',

    /* Generic interface */
    'Properties' => 'Propri&eacute;t&eacute;s',
    'AdvancedProperties' => 'Propri&eacute;t&eacute;s avanc&eacute;es',
);
?>
