<?php
/**
 * @brief CaMykS main french dictionary.
 * @details Engine / Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0pre2
 * @date Creation: Feb 2021
 * @date Modification: Jan 2022
 * @copyright 2021 - 2022 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY,
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$locales = array(
    /* Yes / No */
    'Yes' => 'Oui',
    'No' => 'Non',

    /* Actions */
    'Save'  => 'Enregistrer',
    'Cancel' => 'Annuler',
    'Back' => 'Retour',
    'Continue' => 'Continuer',

    /* Generic interface */
    'Properties' => 'Propri&eacute;t&eacute;s',
    'AdvancedProperties' => 'Propri&eacute;t&eacute;s avanc&eacute;es',

    /* Module library */
    'ObjectStatus_Disabled' => 'D&eacute;sactiv&eacute;',
    'ObjectStatus_Enabled' => 'Activ&eacute;',
    'ObjectStatus_Undefined' => 'Ind&eacute;termin&eacute;',

    'ObjectsStatus_Disabled' => 'D&eacute;sactiv&eacute;s',
    'ObjectsStatus_Enabled' => 'Activ&eacute;s',
    'ObjectsStatus_All' => 'Tous',
);
?>
