<?php
/**
 * @brief DbQuery library french dictionary.
 * @details Engine / Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.0.1
 * @date Creation: Nov 2019
 * @date Modification: Feb 2021
 * @copyright 2019 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY,
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$locales = array(
    'Error_ActionAlreadyDefined' => 'L\'action de cette requecirc;te a d&eacute;j&agrave; &eacute;t&eacute; d&eacute;finie.',
    'Error_ActionUnknown' => 'Action inconnue.',
    'Error_ActionIsNotDefined' => 'Aucune action n\'a &eacute;t&eacute; d&eacute;finie pour cette requ&ecirc;te.',
    'Error_TableIsNull' => 'La table est ind&eacute;termin&eacute;e.',
    'Error_MultiTableIsOnlySupportedBySelectCommand' => 'Les tables multiples ne sont pas support&eacute;es pour cette action.',
    'Error_TableJoinUnknown' => 'Valeur de jointure inconnue.',
    'Error_OrderBySpecialUnknown' => 'Valeur de tri sp&eacute;cial inconnue.',
    'Error_OrderByWayUnknown' => 'Valeur de sens de tri inconnue.',
    'Error_ColumnNameInvalid' => 'Nom de colonne invalide.',
    'Error_ColumnFunctionUnknown' => 'Fonction inconnue.',
    'Error_GroupByDataIsInvalid' => 'Valeur de groupement invalide.',
    'Error_LimitDataIsInvalid' => 'Valeur de limit invalide.',
    'Error_PartitionIsOnlyAvailableWithInsertCommand' => 'L\'ajout d\'une partition n\'est pas support&eacute;e pour cette action.',
    'Error_PartitionDataIsInvalid' => 'Les donn&eacute;es de la partition sont invalides.',
    'Error_ValuesDataIsInvalid' => 'Donn&eacute;es invalides.',
    'Error_ValuesDataHasNotTheSameItemCount' => 'Les donn&eacute;es n\'ont pas le m&ecirc;me nombre d\'&eacute;l&eacute;ments.',
    'Error_ValuesDataDoesNotCorrespondToPartition' => 'Les donn&eacute;es ne correspondent pas &agrave; la partition.',
    'Error_AssignmentIsOnlyAvailableWithUpdateCommand' => 'L\'affection de valeurs n\'est pas support&eacute;e pour cette action.',
    'Error_AssignmentDataIsInvalid' => 'Les donn&eacute;es affect&eacute;es sont invalides.',
);
?>
