<?php
/**
 * @brief CaMykS message page footer.
 * @details Engine / Layout
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Nov 2019
 * @date Modification: Mar 2020
 * @copyright 2019 - 2020 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
?>
    </div>
    <div id="PageFooter">
        <?= $this->name.' '.$this->version; ?>
    </div>
</div>

