<?php
/**
 * @brief CaMykS message page footer.
 * @details Engine / Layout
 * @author CaMykS Team <CaMykS.contact@gmail.com>
 * @version 1.0
 * @date Creation: Nov 2019
 * @date Modification: Nov 2019
 * @copyright 2019 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
global $CaMykS;
?>
            </div>
            <div id="PageFooter">
                <?= $CaMykS->name.' '.$CaMykS->version; ?>
            </div>
        </div>
    </body>
</html>
