<?php
/**
 * @brief CaMykSInstaller plugin, french dictionary.
 * @details Plugin / Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0pre2
 * @date Creation: Jun 2021
 * @date Modification: Nov 2021
 * @copyright 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY,
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$locales = array(
    /* Teader title */
    'TemplateHeaderTitle' => 'Installation du site',

    /* Actions */
    'Action_StartInstallation' => 'D&eacute;marrer l\'installation',
    'Action_Retry' => 'R&eacute;essayer',
    'Action_PerformInstallation' => 'Lancer l\'installation',

    /* Welcome frame */
    'Welcome_Title' => 'Bienvenue sur',
    'Welcome_ConnectionNotSecured' => 'Attention : Votre connexion n\'est pas s&eacute;curis&eacute;e. Vous prenez un risque en vous r&eacute;alisant l\'installation du site. Les donn&eacute;es seront transmises en clair vers le serveur.',

    /* Configuration */
    'UseCaMykSConfiguration' => 'Utiliser la configuration du CMS : %s',

    /* Database messages */
    'Message_DatabaseConnected' => 'Connexion &eacute;tablie au serveur de base de donn&eacute;es.',
    'Message_DatabaseExists' => 'La base de donn&eacute;es existe et sera utilis&eacute;e.',
    'Message_DatabaseDoesntExist' => 'La base de donn&eacute;es n\'existe pas et sera cr&eacute;&eacute;e',

    /* Webmaster configuration */
    'WebmasterConfiguration' => 'Configuration du compte administrateur principal',

    /* Error */
    'Error_ConfigurationFolderIsNotWritable' => 'Le dossier de configuration du site n\'est pas accessible en &eacute;criture.',
);
?>
