<?php
/**
 * @brief CaMykSInstaller plugin, french dictionary.
 * @details Plugin / Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0pre3
 * @date Creation: Jun 2021
 * @date Modification: Jan 2022
 * @copyright 2021 - 2022 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY,
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$locales = array(
    /* Teader title */
    'TemplateHeaderTitle' => 'Installation du site',

    /* Actions */
    'Action_StartInstallation' => 'D&eacute;marrer l\'installation',
    'Action_Retry' => 'R&eacute;essayer',
    'Action_PerformInstallation' => 'Lancer l\'installation',
    'Action_AccessAdmin' => 'Acc&eacute;der &agrave; l\'administration du site',
    'Action_DisplayDetails' => 'Afficher le d&eacute;tail',

    /* Welcome frame */
    'Welcome_Title' => 'Bienvenue sur',
    'Welcome_ConnectionNotSecured' => 'Attention : Votre connexion n\'est pas s&eacute;curis&eacute;e. Vous prenez un risque en vous r&eacute;alisant l\'installation du site. Les donn&eacute;es seront transmises en clair vers le serveur.',

    /* Configuration */
    'UseCaMykSConfiguration' => 'Utiliser la configuration du CMS : %s',

    /* Database messages */
    'Message_DatabaseConnected' => 'Connexion &eacute;tablie au serveur de base de donn&eacute;es.',
    'Message_DatabaseExists' => 'La base de donn&eacute;es existe et sera utilis&eacute;e.',
    'Message_DatabaseDoesntExist' => 'La base de donn&eacute;es n\'existe pas et sera cr&eacute;&eacute;e',

    /* Webmaster configuration */
    'WebmasterConfiguration' => 'Configuration du compte administrateur principal',

    /* Error */
    'Error_ConfigurationFolderIsNotWritable' => 'Le dossier de configuration du site n\'est pas accessible en &eacute;criture.',

    /* Installation done */
    'Installation_Done_Title' => 'Installation termin&eacute;e.',
    'Installation_Done_Message' => 'F&eacute;licitations, l\'installation du site s\'est d&eacute;roul&eacute;e avec succ&egrave;s.',

    /* Installation manifest */
    'Manifest_Title' => 'D&eacute;tail de l\'installation',
    'Manifest_WebsiteInstallationStarted' => 'L\'installation du site a d&eacute;but&eacute;.',
    'Manifest_WebsiteConfigurationFileWritten' => 'Enregistrement du fichier de configuration principal du site.',
    'Manifest_VisitConfigurationFileWritten' => 'Enregistrement du fichier de configuration du mode visite.',
    'Manifest_AdminConfigurationFileWritten' => 'Enregistrement du fichier de configuration du mode administrateur.',
    'Manifest_DatabaseConfigurationFileWritten' => 'Enregistrement du fichier de configuration de la connexion &agrave; la base de donn&eacute;es.',
    'Manifest_DatabaseConnectionCreated' => 'Cr&eacute;ation de la base de donn&eacute;es.',
    'Manifest_DatabaseConnectionOpened' => 'Connexion au service de base de donn&eacute;es.',
    'Manifest_DatabaseOpened' => 'Ouverture de la base de donn&eacute;es.',
    'Manifest_SymLinkCorePluginsAlreadyExists' => 'Utilisation du lien symbolique vers les plugins syst&egrave;me.',
    'Manifest_SymLinkCorePluginsCreated' => 'Cr&eacute;ation du lien symbolique vers les plugins syst&egrave;me.',
    'Manifest_SymLinkSharedPluginsAlreadyExists' => 'Utilisation du lien symbolique vers les plugins partag&eacute;s.',
    'Manifest_SymLinkSharedPluginsCreated' => 'Cr&eacute;ation du lien symbolique vers les plugins partag&eacute;s.',
    'Manifest_SymLinkAssetsAlreadyExists' => 'Utilisation du lien symbolique vers les donn&eacute;es.',
    'Manifest_SymLinkAssetsCreated' => 'Cr&eacute;ation du lien symbolique vers les donn&eacute;es.',
);
?>
