<?php
/**
 * @brief SystemConfigurationManager plugin, french dictionary.
 * @details Plugin / Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0pre2
 * @date Creation: Jun 2021
 * @date Modification: Nov 2021
 * @copyright 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY,
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$locales = array(
    /* Website configuration */
    'WebsiteConfiguration' => 'Param&egrave;tres du site',
    'Title' => 'Titre',
    'Version' => 'Version',
    'Encoding' => 'Encodage',
    'Author' => 'Auteur',
    'CMSSignature' => 'Signature du CMS',
    'LocalStorage' => 'Stockage local',

    /* Admin/Visit configuration */
    'AdminConfiguration' => 'Configuration de l\'espace administrateur',
    'Languages' => 'Langues',
    'DefaultLanguage' => 'Langue par d&eacute;faut',
    'GraphicalAspect' => 'Aspect graphique',
    'Theme' => 'Th&egrave;me',
    'URLs' => 'URLs',
    'SSLMode' => 'Mode SSL',

    /* Admin configuration */
    'EditionLanguages' => 'Langues en &eacute;dition',
    'EntryPoint' => 'Point d\'entr&eacute;e',
    'KeepAlive' => 'Conserver la connexion',
    'SaveMode' => 'Mode d\'enregistrement',

    /* Visit configuration */
    'VisitConfiguration' => 'Configuration de l\'espace visiteur',
    'URLMode' => 'Mode',
    'ServerSideCache' => 'Cache c&ocirc;t&eacute; serveur',
    'ClientSideCache' => 'Cache c&ocirc;t&eacute; client',
    'AutoLoadCaMykSJS' => 'Chargement auto. de CaMykS.js',

    /* Engine configuration */
    'Configuration_TimeZone' => 'Fuseau horaire',
    'Configuration_TimeZoneUndefined' => 'Non d&eacute;fini',
    'Configuration_WebmasterEmail' => 'Email du webmaster',
    'Configuration_WebmasterEmailUndefined' => 'Non d&eacute;fini',
    'Configuration_TemporaryFolder' => 'Dossier temporaire',
    'Configuration_DefaultTemporaryFolder' => 'Dossier temporaire du syst&egrave;me',
    'Configuration_ErrorLogging' => 'Gestion des erreurs',
    'Configuration_ErrorLoggingLevel' => 'Niveau',
    'Configuration_ErrorLoggingLevelUndefined' => 'Non d&eacute;fini',
    'Configuration_ErrorLoggingOutput' => 'Sortie',
    'Configuration_ErrorLoggingOutputUndefined' => 'Non d&eacute;finie',
    'Configuration_DefaultTools' => 'Outils',
    'Configuration_PictureEditor' => 'Editeur d\'images',
    'Configuration_PictureEditorUndefined' => 'Non d&eacute;fini',
    'Configuration_Requests' => 'Requ&ecirc;tes',
    'Configuration_RequestUserAgent' => 'Agent utilisateur',
    'Configuration_RequestUserAgentUndefined' => 'Non d&eacute;fini',

    /* Database configuration */
    'DatabaseConfiguration' => 'Configuration de la connexion &agrave; la base de donn&eacute;es',
    'Driver' => 'Driver',
    'Host' => 'H&ocirc;te',
    'Name' => 'Nom',
    'Login' => 'Identifiant',
    'Password' => 'Mot de passe',
    'Port' => 'Port',
    'Secure' => 'S&eacute;curit&eacute;',
    'TablePrefix' => 'Pr&eacute;fixe des tables',

    /* Display CMS signatures values */
    'DisplayCMSSignature_Hidden' => 'Masqu&eacute;e',
    'DisplayCMSSignature_Display' => 'Affich&eacute;e',

    /* Errors */
    'Error_TitleIsEmpty' => 'Veuillez ins&eacute;rer un titre pour le site internet.',
    'Error_DatabaseNameIsEmpty' => 'Veuillez ins&eacute;rer le nom de la base de donn&eacute;es.',
    'Error_DatabaseDriverIsNotCompatibleWithDatabaseLocalStorage' => 'Les bases de donn&eacute;es %s ne sont pas compatibles avec le stockage local en base de données.',
    'Error_DatabaseCantConnectServer' => 'Impossible de se connecter au serveur de base de donn&eacute;es.',
);
?>
