<?php
/**
 * @brief LocalStorage library french dictionary.
 * @details Engine / Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0pre0
 * @date Creation: Jun 2021
 * @date Modification: Jun 2021
 * @copyright 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY,
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$locales = array(
    'Mode_Files' => 'Fichiers',
    'Mode_Database' => 'Base de donn&eacute;es',
);
?>
